/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante;

import org.xtext.dsl.restaurante.AbstractRestauranteRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RestauranteRuntimeModule extends AbstractRestauranteRuntimeModule {
}
