var code = '<table class="tingredientes">\
	<tr class="tingredientes_cabecera">\
		<th></th>\
		<th>Ingrediente</th>\
		<th>AlÈrgeno</th>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="moluscos (CODI1)" title="moluscos (CODI1)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Molusco" target="_blank">moluscos</a></td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="altramuz (CODI2)" title="altramuz (CODI2)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Anagyris_foetida" target="_blank">altramuz</a></td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="lechuga (CODI3)" title="lechuga (CODI3)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Lechuga" target="_blank">lechuga</a></td>\
		<td><img class="alergenos" src="imagenes/noalergeno.png" alt="Este ingrediente no contiene alÈrgenos" title="Este ingrediente no contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/pollo.jpg" alt="pollo (CODI4)" title="pollo (CODI4)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Pollo" target="_blank">pollo</a></td>\
		<td><img class="alergenos" src="imagenes/noalergeno.png" alt="Este ingrediente no contiene alÈrgenos" title="Este ingrediente no contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/queso.jpg" alt="queso (CODI5)" title="queso (CODI5)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Queso" target="_blank">queso</a></td>\
		<td><img class="alergenos" src="imagenes/noalergeno.png" alt="Este ingrediente no contiene alÈrgenos" title="Este ingrediente no contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="cereales (CODI6)" title="cereales (CODI6)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Cereal" target="_blank">cereales</a></td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="crust√°ceos (CODI7)" title="crust√°ceos (CODI7)" /></td>\
		<td>crust√°ceos</td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/huevos.jpg" alt="huevos (CODI8)" title="huevos (CODI8)" /></td>\
		<td>huevos</td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/pescado.jpg" alt="pescado (CODI9)" title="pescado (CODI9)" /></td>\
		<td>pescado</td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="cacahuetes (CODI10)" title="cacahuetes (CODI10)" /></td>\
		<td>cacahuetes</td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="pan (CODI11)" title="pan (CODI11)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Pan" target="_blank">pan</a></td>\
		<td><img class="alergenos" src="imagenes/noalergeno.png" alt="Este ingrediente no contiene alÈrgenos" title="Este ingrediente no contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="soja (CODI12)" title="soja (CODI12)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Soja" target="_blank">soja</a></td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/leche.jpg" alt="leche (CODI13)" title="leche (CODI13)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Leche" target="_blank">leche</a></td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="frutos secos (CODI14)" title="frutos secos (CODI14)" /></td>\
		<td>frutos secos</td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="apio (CODI15)" title="apio (CODI15)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Apio" target="_blank">apio</a></td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="mostaza (CODI16)" title="mostaza (CODI16)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Mostaza" target="_blank">mostaza</a></td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="semillas de s√©samo (CODI17)" title="semillas de s√©samo (CODI17)" /></td>\
		<td>semillas de s√©samo</td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="di√≥xito de azufre (CODI18)" title="di√≥xito de azufre (CODI18)" /></td>\
		<td>di√≥xito de azufre</td>\
		<td><img class="alergenos" src="imagenes/alergeno.png" alt="Este ingrediente contiene alÈrgenos" title="Este ingrediente contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="croutons (CODI19)" title="croutons (CODI19)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Crouton" target="_blank">croutons</a></td>\
		<td><img class="alergenos" src="imagenes/noalergeno.png" alt="Este ingrediente no contiene alÈrgenos" title="Este ingrediente no contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="tomate (CODI20)" title="tomate (CODI20)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Tomate" target="_blank">tomate</a></td>\
		<td><img class="alergenos" src="imagenes/noalergeno.png" alt="Este ingrediente no contiene alÈrgenos" title="Este ingrediente no contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="pepinillo (CODI21)" title="pepinillo (CODI21)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Pepino" target="_blank">pepinillo</a></td>\
		<td><img class="alergenos" src="imagenes/noalergeno.png" alt="Este ingrediente no contiene alÈrgenos" title="Este ingrediente no contiene alÈrgenos" /></td>\
	</tr>\
	<tr>\
		<td><img class="ingredientes" src="imagenes/generico.jpg" alt="chocolate (CODI22)" title="chocolate (CODI22)" /></td>\
		<td><a href="http://es.wikipedia.org/wiki/Chocolate" target="_blank">chocolate</a></td>\
		<td><img class="alergenos" src="imagenes/noalergeno.png" alt="Este ingrediente no contiene alÈrgenos" title="Este ingrediente no contiene alÈrgenos" /></td>\
	</tr>\
</table>';
