/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.dsl.restaurante.RestauranteRuntimeModule;
import org.xtext.dsl.restaurante.RestauranteStandaloneSetup;
import org.xtext.dsl.restaurante.ide.RestauranteIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RestauranteIdeSetup extends RestauranteStandaloneSetup {
  @Override
  public Injector createInjector() {
    RestauranteRuntimeModule _restauranteRuntimeModule = new RestauranteRuntimeModule();
    RestauranteIdeModule _restauranteIdeModule = new RestauranteIdeModule();
    return Guice.createInjector(Modules2.mixin(_restauranteRuntimeModule, _restauranteIdeModule));
  }
}
