/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.scoping;

import org.xtext.dsl.restaurante.scoping.AbstractRestauranteScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RestauranteScopeProvider extends AbstractRestauranteScopeProvider {
}
