/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RestauranteStandaloneSetup extends RestauranteStandaloneSetupGenerated {

	def static void doSetup() {
		new RestauranteStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
