/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bebida Fria</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.BebidaFria#getDistribuidor <em>Distribuidor</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getBebidaFria()
 * @model
 * @generated
 */
public interface BebidaFria extends Bebida
{
  /**
   * Returns the value of the '<em><b>Distribuidor</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.dsl.restaurante.restaurante.Distribuidor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distribuidor</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distribuidor</em>' attribute.
   * @see org.xtext.dsl.restaurante.restaurante.Distribuidor
   * @see #setDistribuidor(Distribuidor)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getBebidaFria_Distribuidor()
   * @model
   * @generated
   */
  Distribuidor getDistribuidor();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.BebidaFria#getDistribuidor <em>Distribuidor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distribuidor</em>' attribute.
   * @see org.xtext.dsl.restaurante.restaurante.Distribuidor
   * @see #getDistribuidor()
   * @generated
   */
  void setDistribuidor(Distribuidor value);

} // BebidaFria
