/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bebida Caliente</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getBebidaCaliente()
 * @model
 * @generated
 */
public interface BebidaCaliente extends Bebida
{
} // BebidaCaliente
