/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bebida</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getBebida()
 * @model
 * @generated
 */
public interface Bebida extends Producto
{
} // Bebida
