/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Menu#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Menu#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Menu#getDescripcion <em>Descripcion</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Menu#getTamanio <em>Tamanio</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Menu#getFoto <em>Foto</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Menu#getProductos <em>Productos</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getMenu()
 * @model
 * @generated
 */
public interface Menu extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getMenu_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Menu#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' attribute.
   * @see #setNombre(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getMenu_Nombre()
   * @model
   * @generated
   */
  String getNombre();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Menu#getNombre <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' attribute.
   * @see #getNombre()
   * @generated
   */
  void setNombre(String value);

  /**
   * Returns the value of the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Descripcion</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descripcion</em>' attribute.
   * @see #setDescripcion(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getMenu_Descripcion()
   * @model
   * @generated
   */
  String getDescripcion();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Menu#getDescripcion <em>Descripcion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Descripcion</em>' attribute.
   * @see #getDescripcion()
   * @generated
   */
  void setDescripcion(String value);

  /**
   * Returns the value of the '<em><b>Tamanio</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.dsl.restaurante.restaurante.TamanioMenu}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tamanio</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tamanio</em>' attribute.
   * @see org.xtext.dsl.restaurante.restaurante.TamanioMenu
   * @see #setTamanio(TamanioMenu)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getMenu_Tamanio()
   * @model
   * @generated
   */
  TamanioMenu getTamanio();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Menu#getTamanio <em>Tamanio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tamanio</em>' attribute.
   * @see org.xtext.dsl.restaurante.restaurante.TamanioMenu
   * @see #getTamanio()
   * @generated
   */
  void setTamanio(TamanioMenu value);

  /**
   * Returns the value of the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Foto</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foto</em>' attribute.
   * @see #setFoto(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getMenu_Foto()
   * @model
   * @generated
   */
  String getFoto();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Menu#getFoto <em>Foto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Foto</em>' attribute.
   * @see #getFoto()
   * @generated
   */
  void setFoto(String value);

  /**
   * Returns the value of the '<em><b>Productos</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Productos</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Productos</em>' containment reference.
   * @see #setProductos(ProductoY)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getMenu_Productos()
   * @model containment="true"
   * @generated
   */
  ProductoY getProductos();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Menu#getProductos <em>Productos</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Productos</em>' containment reference.
   * @see #getProductos()
   * @generated
   */
  void setProductos(ProductoY value);

} // Menu
