/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nutricional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getCantidad <em>Cantidad</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getUnidad <em>Unidad</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getEnergia <em>Energia</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getGrasas <em>Grasas</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getHidratos <em>Hidratos</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getProteinas <em>Proteinas</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getSal <em>Sal</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getNutricional()
 * @model
 * @generated
 */
public interface Nutricional extends EObject
{
  /**
   * Returns the value of the '<em><b>Cantidad</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cantidad</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cantidad</em>' attribute.
   * @see #setCantidad(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getNutricional_Cantidad()
   * @model
   * @generated
   */
  String getCantidad();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getCantidad <em>Cantidad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cantidad</em>' attribute.
   * @see #getCantidad()
   * @generated
   */
  void setCantidad(String value);

  /**
   * Returns the value of the '<em><b>Unidad</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unidad</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unidad</em>' attribute.
   * @see #setUnidad(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getNutricional_Unidad()
   * @model
   * @generated
   */
  String getUnidad();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getUnidad <em>Unidad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unidad</em>' attribute.
   * @see #getUnidad()
   * @generated
   */
  void setUnidad(String value);

  /**
   * Returns the value of the '<em><b>Energia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Energia</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Energia</em>' attribute.
   * @see #setEnergia(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getNutricional_Energia()
   * @model
   * @generated
   */
  String getEnergia();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getEnergia <em>Energia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Energia</em>' attribute.
   * @see #getEnergia()
   * @generated
   */
  void setEnergia(String value);

  /**
   * Returns the value of the '<em><b>Grasas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Grasas</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grasas</em>' attribute.
   * @see #setGrasas(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getNutricional_Grasas()
   * @model
   * @generated
   */
  String getGrasas();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getGrasas <em>Grasas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Grasas</em>' attribute.
   * @see #getGrasas()
   * @generated
   */
  void setGrasas(String value);

  /**
   * Returns the value of the '<em><b>Hidratos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hidratos</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hidratos</em>' attribute.
   * @see #setHidratos(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getNutricional_Hidratos()
   * @model
   * @generated
   */
  String getHidratos();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getHidratos <em>Hidratos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hidratos</em>' attribute.
   * @see #getHidratos()
   * @generated
   */
  void setHidratos(String value);

  /**
   * Returns the value of the '<em><b>Proteinas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Proteinas</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proteinas</em>' attribute.
   * @see #setProteinas(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getNutricional_Proteinas()
   * @model
   * @generated
   */
  String getProteinas();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getProteinas <em>Proteinas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proteinas</em>' attribute.
   * @see #getProteinas()
   * @generated
   */
  void setProteinas(String value);

  /**
   * Returns the value of the '<em><b>Sal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sal</em>' attribute.
   * @see #setSal(String)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getNutricional_Sal()
   * @model
   * @generated
   */
  String getSal();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getSal <em>Sal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sal</em>' attribute.
   * @see #getSal()
   * @generated
   */
  void setSal(String value);

} // Nutricional
