/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Postre</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Postre#isHelado <em>Helado</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Postre#getDistribuidor <em>Distribuidor</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Postre#getIngredientes <em>Ingredientes</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getPostre()
 * @model
 * @generated
 */
public interface Postre extends Producto
{
  /**
   * Returns the value of the '<em><b>Helado</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Helado</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Helado</em>' attribute.
   * @see #setHelado(boolean)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getPostre_Helado()
   * @model
   * @generated
   */
  boolean isHelado();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Postre#isHelado <em>Helado</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Helado</em>' attribute.
   * @see #isHelado()
   * @generated
   */
  void setHelado(boolean value);

  /**
   * Returns the value of the '<em><b>Distribuidor</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.dsl.restaurante.restaurante.Distribuidor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distribuidor</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distribuidor</em>' attribute.
   * @see org.xtext.dsl.restaurante.restaurante.Distribuidor
   * @see #setDistribuidor(Distribuidor)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getPostre_Distribuidor()
   * @model
   * @generated
   */
  Distribuidor getDistribuidor();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Postre#getDistribuidor <em>Distribuidor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distribuidor</em>' attribute.
   * @see org.xtext.dsl.restaurante.restaurante.Distribuidor
   * @see #getDistribuidor()
   * @generated
   */
  void setDistribuidor(Distribuidor value);

  /**
   * Returns the value of the '<em><b>Ingredientes</b></em>' reference list.
   * The list contents are of type {@link org.xtext.dsl.restaurante.restaurante.Ingrediente}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ingredientes</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ingredientes</em>' reference list.
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getPostre_Ingredientes()
   * @model
   * @generated
   */
  EList<Ingrediente> getIngredientes();

} // Postre
