/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Principal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Principal#isEnsalada <em>Ensalada</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Principal#getIngredientes <em>Ingredientes</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.Principal#getSalsa <em>Salsa</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getPrincipal()
 * @model
 * @generated
 */
public interface Principal extends Producto
{
  /**
   * Returns the value of the '<em><b>Ensalada</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ensalada</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ensalada</em>' attribute.
   * @see #setEnsalada(boolean)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getPrincipal_Ensalada()
   * @model
   * @generated
   */
  boolean isEnsalada();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Principal#isEnsalada <em>Ensalada</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ensalada</em>' attribute.
   * @see #isEnsalada()
   * @generated
   */
  void setEnsalada(boolean value);

  /**
   * Returns the value of the '<em><b>Ingredientes</b></em>' reference list.
   * The list contents are of type {@link org.xtext.dsl.restaurante.restaurante.Ingrediente}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ingredientes</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ingredientes</em>' reference list.
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getPrincipal_Ingredientes()
   * @model
   * @generated
   */
  EList<Ingrediente> getIngredientes();

  /**
   * Returns the value of the '<em><b>Salsa</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.dsl.restaurante.restaurante.SalsaRecomendada}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Salsa</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Salsa</em>' attribute.
   * @see org.xtext.dsl.restaurante.restaurante.SalsaRecomendada
   * @see #setSalsa(SalsaRecomendada)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getPrincipal_Salsa()
   * @model
   * @generated
   */
  SalsaRecomendada getSalsa();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.Principal#getSalsa <em>Salsa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Salsa</em>' attribute.
   * @see org.xtext.dsl.restaurante.restaurante.SalsaRecomendada
   * @see #getSalsa()
   * @generated
   */
  void setSalsa(SalsaRecomendada value);

} // Principal
