/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Producto Y</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.ProductoY#getIzq <em>Izq</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.ProductoY#getDer <em>Der</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getProductoY()
 * @model
 * @generated
 */
public interface ProductoY extends EObject
{
  /**
   * Returns the value of the '<em><b>Izq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Izq</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Izq</em>' containment reference.
   * @see #setIzq(ProductoO)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getProductoY_Izq()
   * @model containment="true"
   * @generated
   */
  ProductoO getIzq();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.ProductoY#getIzq <em>Izq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Izq</em>' containment reference.
   * @see #getIzq()
   * @generated
   */
  void setIzq(ProductoO value);

  /**
   * Returns the value of the '<em><b>Der</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dsl.restaurante.restaurante.ProductoO}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Der</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Der</em>' containment reference list.
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getProductoY_Der()
   * @model containment="true"
   * @generated
   */
  EList<ProductoO> getDer();

} // ProductoY
