/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Producto O</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.ProductoO#getIzq <em>Izq</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.ProductoO#getDer <em>Der</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getProductoO()
 * @model
 * @generated
 */
public interface ProductoO extends EObject
{
  /**
   * Returns the value of the '<em><b>Izq</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Izq</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Izq</em>' reference.
   * @see #setIzq(Producto)
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getProductoO_Izq()
   * @model
   * @generated
   */
  Producto getIzq();

  /**
   * Sets the value of the '{@link org.xtext.dsl.restaurante.restaurante.ProductoO#getIzq <em>Izq</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Izq</em>' reference.
   * @see #getIzq()
   * @generated
   */
  void setIzq(Producto value);

  /**
   * Returns the value of the '<em><b>Der</b></em>' reference list.
   * The list contents are of type {@link org.xtext.dsl.restaurante.restaurante.Producto}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Der</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Der</em>' reference list.
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#getProductoO_Der()
   * @model
   * @generated
   */
  EList<Producto> getDer();

} // ProductoO
