/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.restaurante.restaurante.RestauranteFactory
 * @model kind="package"
 * @generated
 */
public interface RestaurantePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "restaurante";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/dsl/restaurante/Restaurante";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "restaurante";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RestaurantePackage eINSTANCE = org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.RestauranteImpl <em>Restaurante</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestauranteImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getRestaurante()
   * @generated
   */
  int RESTAURANTE = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE__NOMBRE = 0;

  /**
   * The feature id for the '<em><b>Fecha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE__FECHA = 1;

  /**
   * The feature id for the '<em><b>Ingredientes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE__INGREDIENTES = 2;

  /**
   * The feature id for the '<em><b>Productos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE__PRODUCTOS = 3;

  /**
   * The feature id for the '<em><b>Menus</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE__MENUS = 4;

  /**
   * The number of structural features of the '<em>Restaurante</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl <em>Ingrediente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getIngrediente()
   * @generated
   */
  int INGREDIENTE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__NOMBRE = 1;

  /**
   * The feature id for the '<em><b>Info URL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__INFO_URL = 2;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__FOTO = 3;

  /**
   * The feature id for the '<em><b>Alergenico</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__ALERGENICO = 4;

  /**
   * The number of structural features of the '<em>Ingrediente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.ProductoImpl <em>Producto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.ProductoImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getProducto()
   * @generated
   */
  int PRODUCTO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__NAME = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__NOMBRE = 1;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__DESCRIPCION = 2;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__FOTO = 3;

  /**
   * The feature id for the '<em><b>Nutricional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__NUTRICIONAL = 4;

  /**
   * The number of structural features of the '<em>Producto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.PrincipalImpl <em>Principal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.PrincipalImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getPrincipal()
   * @generated
   */
  int PRINCIPAL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL__NAME = PRODUCTO__NAME;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL__NOMBRE = PRODUCTO__NOMBRE;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL__DESCRIPCION = PRODUCTO__DESCRIPCION;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL__FOTO = PRODUCTO__FOTO;

  /**
   * The feature id for the '<em><b>Nutricional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL__NUTRICIONAL = PRODUCTO__NUTRICIONAL;

  /**
   * The feature id for the '<em><b>Ensalada</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL__ENSALADA = PRODUCTO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ingredientes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL__INGREDIENTES = PRODUCTO_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Salsa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL__SALSA = PRODUCTO_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Principal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINCIPAL_FEATURE_COUNT = PRODUCTO_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.ComplementoImpl <em>Complemento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.ComplementoImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getComplemento()
   * @generated
   */
  int COMPLEMENTO = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENTO__NAME = PRODUCTO__NAME;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENTO__NOMBRE = PRODUCTO__NOMBRE;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENTO__DESCRIPCION = PRODUCTO__DESCRIPCION;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENTO__FOTO = PRODUCTO__FOTO;

  /**
   * The feature id for the '<em><b>Nutricional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENTO__NUTRICIONAL = PRODUCTO__NUTRICIONAL;

  /**
   * The number of structural features of the '<em>Complemento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENTO_FEATURE_COUNT = PRODUCTO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.BebidaImpl <em>Bebida</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.BebidaImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getBebida()
   * @generated
   */
  int BEBIDA = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA__NAME = PRODUCTO__NAME;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA__NOMBRE = PRODUCTO__NOMBRE;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA__DESCRIPCION = PRODUCTO__DESCRIPCION;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA__FOTO = PRODUCTO__FOTO;

  /**
   * The feature id for the '<em><b>Nutricional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA__NUTRICIONAL = PRODUCTO__NUTRICIONAL;

  /**
   * The number of structural features of the '<em>Bebida</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_FEATURE_COUNT = PRODUCTO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.BebidaFriaImpl <em>Bebida Fria</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.BebidaFriaImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getBebidaFria()
   * @generated
   */
  int BEBIDA_FRIA = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_FRIA__NAME = BEBIDA__NAME;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_FRIA__NOMBRE = BEBIDA__NOMBRE;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_FRIA__DESCRIPCION = BEBIDA__DESCRIPCION;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_FRIA__FOTO = BEBIDA__FOTO;

  /**
   * The feature id for the '<em><b>Nutricional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_FRIA__NUTRICIONAL = BEBIDA__NUTRICIONAL;

  /**
   * The feature id for the '<em><b>Distribuidor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_FRIA__DISTRIBUIDOR = BEBIDA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bebida Fria</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_FRIA_FEATURE_COUNT = BEBIDA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.BebidaCalienteImpl <em>Bebida Caliente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.BebidaCalienteImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getBebidaCaliente()
   * @generated
   */
  int BEBIDA_CALIENTE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_CALIENTE__NAME = BEBIDA__NAME;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_CALIENTE__NOMBRE = BEBIDA__NOMBRE;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_CALIENTE__DESCRIPCION = BEBIDA__DESCRIPCION;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_CALIENTE__FOTO = BEBIDA__FOTO;

  /**
   * The feature id for the '<em><b>Nutricional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_CALIENTE__NUTRICIONAL = BEBIDA__NUTRICIONAL;

  /**
   * The number of structural features of the '<em>Bebida Caliente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEBIDA_CALIENTE_FEATURE_COUNT = BEBIDA_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.PostreImpl <em>Postre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.PostreImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getPostre()
   * @generated
   */
  int POSTRE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE__NAME = PRODUCTO__NAME;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE__NOMBRE = PRODUCTO__NOMBRE;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE__DESCRIPCION = PRODUCTO__DESCRIPCION;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE__FOTO = PRODUCTO__FOTO;

  /**
   * The feature id for the '<em><b>Nutricional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE__NUTRICIONAL = PRODUCTO__NUTRICIONAL;

  /**
   * The feature id for the '<em><b>Helado</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE__HELADO = PRODUCTO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Distribuidor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE__DISTRIBUIDOR = PRODUCTO_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ingredientes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE__INGREDIENTES = PRODUCTO_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Postre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTRE_FEATURE_COUNT = PRODUCTO_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl <em>Nutricional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getNutricional()
   * @generated
   */
  int NUTRICIONAL = 9;

  /**
   * The feature id for the '<em><b>Cantidad</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTRICIONAL__CANTIDAD = 0;

  /**
   * The feature id for the '<em><b>Unidad</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTRICIONAL__UNIDAD = 1;

  /**
   * The feature id for the '<em><b>Energia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTRICIONAL__ENERGIA = 2;

  /**
   * The feature id for the '<em><b>Grasas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTRICIONAL__GRASAS = 3;

  /**
   * The feature id for the '<em><b>Hidratos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTRICIONAL__HIDRATOS = 4;

  /**
   * The feature id for the '<em><b>Proteinas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTRICIONAL__PROTEINAS = 5;

  /**
   * The feature id for the '<em><b>Sal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTRICIONAL__SAL = 6;

  /**
   * The number of structural features of the '<em>Nutricional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTRICIONAL_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.MenuImpl <em>Menu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.MenuImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getMenu()
   * @generated
   */
  int MENU = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__NAME = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__NOMBRE = 1;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__DESCRIPCION = 2;

  /**
   * The feature id for the '<em><b>Tamanio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__TAMANIO = 3;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__FOTO = 4;

  /**
   * The feature id for the '<em><b>Productos</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU__PRODUCTOS = 5;

  /**
   * The number of structural features of the '<em>Menu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MENU_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.ProductoYImpl <em>Producto Y</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.ProductoYImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getProductoY()
   * @generated
   */
  int PRODUCTO_Y = 11;

  /**
   * The feature id for the '<em><b>Izq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO_Y__IZQ = 0;

  /**
   * The feature id for the '<em><b>Der</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO_Y__DER = 1;

  /**
   * The number of structural features of the '<em>Producto Y</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO_Y_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.ProductoOImpl <em>Producto O</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.ProductoOImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getProductoO()
   * @generated
   */
  int PRODUCTO_O = 12;

  /**
   * The feature id for the '<em><b>Izq</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO_O__IZQ = 0;

  /**
   * The feature id for the '<em><b>Der</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO_O__DER = 1;

  /**
   * The number of structural features of the '<em>Producto O</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO_O_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.SalsaRecomendada <em>Salsa Recomendada</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.SalsaRecomendada
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getSalsaRecomendada()
   * @generated
   */
  int SALSA_RECOMENDADA = 13;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.TamanioMenu <em>Tamanio Menu</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.TamanioMenu
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getTamanioMenu()
   * @generated
   */
  int TAMANIO_MENU = 14;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.Distribuidor <em>Distribuidor</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.Distribuidor
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getDistribuidor()
   * @generated
   */
  int DISTRIBUIDOR = 15;


  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Restaurante <em>Restaurante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Restaurante</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante
   * @generated
   */
  EClass getRestaurante();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Restaurante#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante#getNombre()
   * @see #getRestaurante()
   * @generated
   */
  EAttribute getRestaurante_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Restaurante#getFecha <em>Fecha</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fecha</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante#getFecha()
   * @see #getRestaurante()
   * @generated
   */
  EAttribute getRestaurante_Fecha();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.restaurante.restaurante.Restaurante#getIngredientes <em>Ingredientes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ingredientes</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante#getIngredientes()
   * @see #getRestaurante()
   * @generated
   */
  EReference getRestaurante_Ingredientes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.restaurante.restaurante.Restaurante#getProductos <em>Productos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Productos</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante#getProductos()
   * @see #getRestaurante()
   * @generated
   */
  EReference getRestaurante_Productos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.restaurante.restaurante.Restaurante#getMenus <em>Menus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Menus</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante#getMenus()
   * @see #getRestaurante()
   * @generated
   */
  EReference getRestaurante_Menus();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente <em>Ingrediente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingrediente</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente
   * @generated
   */
  EClass getIngrediente();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#getName()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#getNombre()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#getInfoURL <em>Info URL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Info URL</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#getInfoURL()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_InfoURL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#getFoto <em>Foto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Foto</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#getFoto()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Foto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#isAlergenico <em>Alergenico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alergenico</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#isAlergenico()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Alergenico();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Producto <em>Producto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Producto</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Producto
   * @generated
   */
  EClass getProducto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Producto#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Producto#getName()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Producto#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Producto#getNombre()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Producto#getDescripcion <em>Descripcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Descripcion</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Producto#getDescripcion()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Descripcion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Producto#getFoto <em>Foto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Foto</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Producto#getFoto()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Foto();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.dsl.restaurante.restaurante.Producto#getNutricional <em>Nutricional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nutricional</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Producto#getNutricional()
   * @see #getProducto()
   * @generated
   */
  EReference getProducto_Nutricional();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Principal <em>Principal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Principal</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Principal
   * @generated
   */
  EClass getPrincipal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Principal#isEnsalada <em>Ensalada</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ensalada</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Principal#isEnsalada()
   * @see #getPrincipal()
   * @generated
   */
  EAttribute getPrincipal_Ensalada();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.dsl.restaurante.restaurante.Principal#getIngredientes <em>Ingredientes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Ingredientes</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Principal#getIngredientes()
   * @see #getPrincipal()
   * @generated
   */
  EReference getPrincipal_Ingredientes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Principal#getSalsa <em>Salsa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Salsa</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Principal#getSalsa()
   * @see #getPrincipal()
   * @generated
   */
  EAttribute getPrincipal_Salsa();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Complemento <em>Complemento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complemento</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Complemento
   * @generated
   */
  EClass getComplemento();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Bebida <em>Bebida</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bebida</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Bebida
   * @generated
   */
  EClass getBebida();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.BebidaFria <em>Bebida Fria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bebida Fria</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.BebidaFria
   * @generated
   */
  EClass getBebidaFria();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.BebidaFria#getDistribuidor <em>Distribuidor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distribuidor</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.BebidaFria#getDistribuidor()
   * @see #getBebidaFria()
   * @generated
   */
  EAttribute getBebidaFria_Distribuidor();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.BebidaCaliente <em>Bebida Caliente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bebida Caliente</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.BebidaCaliente
   * @generated
   */
  EClass getBebidaCaliente();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Postre <em>Postre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Postre</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Postre
   * @generated
   */
  EClass getPostre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Postre#isHelado <em>Helado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Helado</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Postre#isHelado()
   * @see #getPostre()
   * @generated
   */
  EAttribute getPostre_Helado();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Postre#getDistribuidor <em>Distribuidor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distribuidor</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Postre#getDistribuidor()
   * @see #getPostre()
   * @generated
   */
  EAttribute getPostre_Distribuidor();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.dsl.restaurante.restaurante.Postre#getIngredientes <em>Ingredientes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Ingredientes</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Postre#getIngredientes()
   * @see #getPostre()
   * @generated
   */
  EReference getPostre_Ingredientes();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Nutricional <em>Nutricional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nutricional</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Nutricional
   * @generated
   */
  EClass getNutricional();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getCantidad <em>Cantidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cantidad</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Nutricional#getCantidad()
   * @see #getNutricional()
   * @generated
   */
  EAttribute getNutricional_Cantidad();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getUnidad <em>Unidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unidad</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Nutricional#getUnidad()
   * @see #getNutricional()
   * @generated
   */
  EAttribute getNutricional_Unidad();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getEnergia <em>Energia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Energia</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Nutricional#getEnergia()
   * @see #getNutricional()
   * @generated
   */
  EAttribute getNutricional_Energia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getGrasas <em>Grasas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Grasas</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Nutricional#getGrasas()
   * @see #getNutricional()
   * @generated
   */
  EAttribute getNutricional_Grasas();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getHidratos <em>Hidratos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hidratos</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Nutricional#getHidratos()
   * @see #getNutricional()
   * @generated
   */
  EAttribute getNutricional_Hidratos();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getProteinas <em>Proteinas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proteinas</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Nutricional#getProteinas()
   * @see #getNutricional()
   * @generated
   */
  EAttribute getNutricional_Proteinas();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Nutricional#getSal <em>Sal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sal</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Nutricional#getSal()
   * @see #getNutricional()
   * @generated
   */
  EAttribute getNutricional_Sal();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Menu <em>Menu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Menu</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Menu
   * @generated
   */
  EClass getMenu();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Menu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Menu#getName()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Menu#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Menu#getNombre()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Menu#getDescripcion <em>Descripcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Descripcion</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Menu#getDescripcion()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Descripcion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Menu#getTamanio <em>Tamanio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tamanio</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Menu#getTamanio()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Tamanio();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Menu#getFoto <em>Foto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Foto</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Menu#getFoto()
   * @see #getMenu()
   * @generated
   */
  EAttribute getMenu_Foto();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.dsl.restaurante.restaurante.Menu#getProductos <em>Productos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Productos</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Menu#getProductos()
   * @see #getMenu()
   * @generated
   */
  EReference getMenu_Productos();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.ProductoY <em>Producto Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Producto Y</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.ProductoY
   * @generated
   */
  EClass getProductoY();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.dsl.restaurante.restaurante.ProductoY#getIzq <em>Izq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Izq</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.ProductoY#getIzq()
   * @see #getProductoY()
   * @generated
   */
  EReference getProductoY_Izq();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.restaurante.restaurante.ProductoY#getDer <em>Der</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Der</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.ProductoY#getDer()
   * @see #getProductoY()
   * @generated
   */
  EReference getProductoY_Der();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.ProductoO <em>Producto O</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Producto O</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.ProductoO
   * @generated
   */
  EClass getProductoO();

  /**
   * Returns the meta object for the reference '{@link org.xtext.dsl.restaurante.restaurante.ProductoO#getIzq <em>Izq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Izq</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.ProductoO#getIzq()
   * @see #getProductoO()
   * @generated
   */
  EReference getProductoO_Izq();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.dsl.restaurante.restaurante.ProductoO#getDer <em>Der</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Der</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.ProductoO#getDer()
   * @see #getProductoO()
   * @generated
   */
  EReference getProductoO_Der();

  /**
   * Returns the meta object for enum '{@link org.xtext.dsl.restaurante.restaurante.SalsaRecomendada <em>Salsa Recomendada</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Salsa Recomendada</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.SalsaRecomendada
   * @generated
   */
  EEnum getSalsaRecomendada();

  /**
   * Returns the meta object for enum '{@link org.xtext.dsl.restaurante.restaurante.TamanioMenu <em>Tamanio Menu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Tamanio Menu</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.TamanioMenu
   * @generated
   */
  EEnum getTamanioMenu();

  /**
   * Returns the meta object for enum '{@link org.xtext.dsl.restaurante.restaurante.Distribuidor <em>Distribuidor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Distribuidor</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Distribuidor
   * @generated
   */
  EEnum getDistribuidor();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RestauranteFactory getRestauranteFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.RestauranteImpl <em>Restaurante</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestauranteImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getRestaurante()
     * @generated
     */
    EClass RESTAURANTE = eINSTANCE.getRestaurante();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTAURANTE__NOMBRE = eINSTANCE.getRestaurante_Nombre();

    /**
     * The meta object literal for the '<em><b>Fecha</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTAURANTE__FECHA = eINSTANCE.getRestaurante_Fecha();

    /**
     * The meta object literal for the '<em><b>Ingredientes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESTAURANTE__INGREDIENTES = eINSTANCE.getRestaurante_Ingredientes();

    /**
     * The meta object literal for the '<em><b>Productos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESTAURANTE__PRODUCTOS = eINSTANCE.getRestaurante_Productos();

    /**
     * The meta object literal for the '<em><b>Menus</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESTAURANTE__MENUS = eINSTANCE.getRestaurante_Menus();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl <em>Ingrediente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getIngrediente()
     * @generated
     */
    EClass INGREDIENTE = eINSTANCE.getIngrediente();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__NAME = eINSTANCE.getIngrediente_Name();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__NOMBRE = eINSTANCE.getIngrediente_Nombre();

    /**
     * The meta object literal for the '<em><b>Info URL</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__INFO_URL = eINSTANCE.getIngrediente_InfoURL();

    /**
     * The meta object literal for the '<em><b>Foto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__FOTO = eINSTANCE.getIngrediente_Foto();

    /**
     * The meta object literal for the '<em><b>Alergenico</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__ALERGENICO = eINSTANCE.getIngrediente_Alergenico();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.ProductoImpl <em>Producto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.ProductoImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getProducto()
     * @generated
     */
    EClass PRODUCTO = eINSTANCE.getProducto();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__NAME = eINSTANCE.getProducto_Name();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__NOMBRE = eINSTANCE.getProducto_Nombre();

    /**
     * The meta object literal for the '<em><b>Descripcion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__DESCRIPCION = eINSTANCE.getProducto_Descripcion();

    /**
     * The meta object literal for the '<em><b>Foto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__FOTO = eINSTANCE.getProducto_Foto();

    /**
     * The meta object literal for the '<em><b>Nutricional</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTO__NUTRICIONAL = eINSTANCE.getProducto_Nutricional();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.PrincipalImpl <em>Principal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.PrincipalImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getPrincipal()
     * @generated
     */
    EClass PRINCIPAL = eINSTANCE.getPrincipal();

    /**
     * The meta object literal for the '<em><b>Ensalada</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRINCIPAL__ENSALADA = eINSTANCE.getPrincipal_Ensalada();

    /**
     * The meta object literal for the '<em><b>Ingredientes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINCIPAL__INGREDIENTES = eINSTANCE.getPrincipal_Ingredientes();

    /**
     * The meta object literal for the '<em><b>Salsa</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRINCIPAL__SALSA = eINSTANCE.getPrincipal_Salsa();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.ComplementoImpl <em>Complemento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.ComplementoImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getComplemento()
     * @generated
     */
    EClass COMPLEMENTO = eINSTANCE.getComplemento();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.BebidaImpl <em>Bebida</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.BebidaImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getBebida()
     * @generated
     */
    EClass BEBIDA = eINSTANCE.getBebida();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.BebidaFriaImpl <em>Bebida Fria</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.BebidaFriaImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getBebidaFria()
     * @generated
     */
    EClass BEBIDA_FRIA = eINSTANCE.getBebidaFria();

    /**
     * The meta object literal for the '<em><b>Distribuidor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEBIDA_FRIA__DISTRIBUIDOR = eINSTANCE.getBebidaFria_Distribuidor();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.BebidaCalienteImpl <em>Bebida Caliente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.BebidaCalienteImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getBebidaCaliente()
     * @generated
     */
    EClass BEBIDA_CALIENTE = eINSTANCE.getBebidaCaliente();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.PostreImpl <em>Postre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.PostreImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getPostre()
     * @generated
     */
    EClass POSTRE = eINSTANCE.getPostre();

    /**
     * The meta object literal for the '<em><b>Helado</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSTRE__HELADO = eINSTANCE.getPostre_Helado();

    /**
     * The meta object literal for the '<em><b>Distribuidor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSTRE__DISTRIBUIDOR = eINSTANCE.getPostre_Distribuidor();

    /**
     * The meta object literal for the '<em><b>Ingredientes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POSTRE__INGREDIENTES = eINSTANCE.getPostre_Ingredientes();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl <em>Nutricional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getNutricional()
     * @generated
     */
    EClass NUTRICIONAL = eINSTANCE.getNutricional();

    /**
     * The meta object literal for the '<em><b>Cantidad</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTRICIONAL__CANTIDAD = eINSTANCE.getNutricional_Cantidad();

    /**
     * The meta object literal for the '<em><b>Unidad</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTRICIONAL__UNIDAD = eINSTANCE.getNutricional_Unidad();

    /**
     * The meta object literal for the '<em><b>Energia</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTRICIONAL__ENERGIA = eINSTANCE.getNutricional_Energia();

    /**
     * The meta object literal for the '<em><b>Grasas</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTRICIONAL__GRASAS = eINSTANCE.getNutricional_Grasas();

    /**
     * The meta object literal for the '<em><b>Hidratos</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTRICIONAL__HIDRATOS = eINSTANCE.getNutricional_Hidratos();

    /**
     * The meta object literal for the '<em><b>Proteinas</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTRICIONAL__PROTEINAS = eINSTANCE.getNutricional_Proteinas();

    /**
     * The meta object literal for the '<em><b>Sal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTRICIONAL__SAL = eINSTANCE.getNutricional_Sal();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.MenuImpl <em>Menu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.MenuImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getMenu()
     * @generated
     */
    EClass MENU = eINSTANCE.getMenu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__NAME = eINSTANCE.getMenu_Name();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__NOMBRE = eINSTANCE.getMenu_Nombre();

    /**
     * The meta object literal for the '<em><b>Descripcion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__DESCRIPCION = eINSTANCE.getMenu_Descripcion();

    /**
     * The meta object literal for the '<em><b>Tamanio</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__TAMANIO = eINSTANCE.getMenu_Tamanio();

    /**
     * The meta object literal for the '<em><b>Foto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MENU__FOTO = eINSTANCE.getMenu_Foto();

    /**
     * The meta object literal for the '<em><b>Productos</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MENU__PRODUCTOS = eINSTANCE.getMenu_Productos();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.ProductoYImpl <em>Producto Y</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.ProductoYImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getProductoY()
     * @generated
     */
    EClass PRODUCTO_Y = eINSTANCE.getProductoY();

    /**
     * The meta object literal for the '<em><b>Izq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTO_Y__IZQ = eINSTANCE.getProductoY_Izq();

    /**
     * The meta object literal for the '<em><b>Der</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTO_Y__DER = eINSTANCE.getProductoY_Der();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.ProductoOImpl <em>Producto O</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.ProductoOImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getProductoO()
     * @generated
     */
    EClass PRODUCTO_O = eINSTANCE.getProductoO();

    /**
     * The meta object literal for the '<em><b>Izq</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTO_O__IZQ = eINSTANCE.getProductoO_Izq();

    /**
     * The meta object literal for the '<em><b>Der</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTO_O__DER = eINSTANCE.getProductoO_Der();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.SalsaRecomendada <em>Salsa Recomendada</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.SalsaRecomendada
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getSalsaRecomendada()
     * @generated
     */
    EEnum SALSA_RECOMENDADA = eINSTANCE.getSalsaRecomendada();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.TamanioMenu <em>Tamanio Menu</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.TamanioMenu
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getTamanioMenu()
     * @generated
     */
    EEnum TAMANIO_MENU = eINSTANCE.getTamanioMenu();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.Distribuidor <em>Distribuidor</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.Distribuidor
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getDistribuidor()
     * @generated
     */
    EEnum DISTRIBUIDOR = eINSTANCE.getDistribuidor();

  }

} //RestaurantePackage
