/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RestauranteAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/dsl/restaurante/parser/antlr/internal/InternalRestaurante.tokens");
	}
}
