/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RestauranteGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RestauranteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Restaurante");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRestaurantesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreSTRINGTerminalRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		private final Keyword cFechaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFechaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFechaFECHATerminalRuleCall_3_0 = (RuleCall)cFechaAssignment_3.eContents().get(0);
		private final Keyword cIngredientesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cIngredientesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cIngredientesIngredienteParserRuleCall_6_0 = (RuleCall)cIngredientesAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cProductosKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cProductosAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cProductosProductoParserRuleCall_10_0 = (RuleCall)cProductosAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cMenusKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cMenusAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cMenusMenuParserRuleCall_14_0 = (RuleCall)cMenusAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Restaurante:
		//	'Restaurantes' nombre=STRING
		//	'fecha' fecha=FECHA
		//	'Ingredientes' '{'
		//	ingredientes+=Ingrediente*
		//	'}'
		//	'Productos' '{'
		//	productos+=Producto*
		//	'}'
		//	'Menus' '{'
		//	menus+=Menu*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Restaurantes' nombre=STRING 'fecha' fecha=FECHA 'Ingredientes' '{' ingredientes+=Ingrediente* '}' 'Productos' '{'
		//productos+=Producto* '}' 'Menus' '{' menus+=Menu* '}'
		public Group getGroup() { return cGroup; }
		
		//'Restaurantes'
		public Keyword getRestaurantesKeyword_0() { return cRestaurantesKeyword_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_1_0() { return cNombreSTRINGTerminalRuleCall_1_0; }
		
		//'fecha'
		public Keyword getFechaKeyword_2() { return cFechaKeyword_2; }
		
		//fecha=FECHA
		public Assignment getFechaAssignment_3() { return cFechaAssignment_3; }
		
		//FECHA
		public RuleCall getFechaFECHATerminalRuleCall_3_0() { return cFechaFECHATerminalRuleCall_3_0; }
		
		//'Ingredientes'
		public Keyword getIngredientesKeyword_4() { return cIngredientesKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//ingredientes+=Ingrediente*
		public Assignment getIngredientesAssignment_6() { return cIngredientesAssignment_6; }
		
		//Ingrediente
		public RuleCall getIngredientesIngredienteParserRuleCall_6_0() { return cIngredientesIngredienteParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'Productos'
		public Keyword getProductosKeyword_8() { return cProductosKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//productos+=Producto*
		public Assignment getProductosAssignment_10() { return cProductosAssignment_10; }
		
		//Producto
		public RuleCall getProductosProductoParserRuleCall_10_0() { return cProductosProductoParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'Menus'
		public Keyword getMenusKeyword_12() { return cMenusKeyword_12; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }
		
		//menus+=Menu*
		public Assignment getMenusAssignment_14() { return cMenusAssignment_14; }
		
		//Menu
		public RuleCall getMenusMenuParserRuleCall_14_0() { return cMenusMenuParserRuleCall_14_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class IngredienteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Ingrediente");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIngredienteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cInfoURLKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cInfoURLAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cInfoURLURLTerminalRuleCall_3_1_0 = (RuleCall)cInfoURLAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFotoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFotoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFotoSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cFotoAssignment_4_1.eContents().get(0);
		private final Assignment cAlergenicoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cAlergenicoAlergenicoKeyword_5_0 = (Keyword)cAlergenicoAssignment_5.eContents().get(0);
		
		//Ingrediente:
		//	'Ingrediente:' name=ID
		//	nombre=STRING ('infoURL:' infoURL=URL)? ('foto:' foto=STRING)?
		//	alergenico?='alergenico'?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Ingrediente:' name=ID nombre=STRING ('infoURL:' infoURL=URL)? ('foto:' foto=STRING)? alergenico?='alergenico'?
		public Group getGroup() { return cGroup; }
		
		//'Ingrediente:'
		public Keyword getIngredienteKeyword_0() { return cIngredienteKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//('infoURL:' infoURL=URL)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'infoURL:'
		public Keyword getInfoURLKeyword_3_0() { return cInfoURLKeyword_3_0; }
		
		//infoURL=URL
		public Assignment getInfoURLAssignment_3_1() { return cInfoURLAssignment_3_1; }
		
		//URL
		public RuleCall getInfoURLURLTerminalRuleCall_3_1_0() { return cInfoURLURLTerminalRuleCall_3_1_0; }
		
		//('foto:' foto=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'foto:'
		public Keyword getFotoKeyword_4_0() { return cFotoKeyword_4_0; }
		
		//foto=STRING
		public Assignment getFotoAssignment_4_1() { return cFotoAssignment_4_1; }
		
		//STRING
		public RuleCall getFotoSTRINGTerminalRuleCall_4_1_0() { return cFotoSTRINGTerminalRuleCall_4_1_0; }
		
		//alergenico?='alergenico'?
		public Assignment getAlergenicoAssignment_5() { return cAlergenicoAssignment_5; }
		
		//'alergenico'
		public Keyword getAlergenicoAlergenicoKeyword_5_0() { return cAlergenicoAlergenicoKeyword_5_0; }
	}
	public class ProductoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Producto");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPrincipalParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComplementoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBebidaParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cPostreParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Producto:
		//	Principal | Complemento | Bebida | Postre;
		@Override public ParserRule getRule() { return rule; }
		
		//Principal | Complemento | Bebida | Postre
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Principal
		public RuleCall getPrincipalParserRuleCall_0() { return cPrincipalParserRuleCall_0; }
		
		//Complemento
		public RuleCall getComplementoParserRuleCall_1() { return cComplementoParserRuleCall_1; }
		
		//Bebida
		public RuleCall getBebidaParserRuleCall_2() { return cBebidaParserRuleCall_2; }
		
		//Postre
		public RuleCall getPostreParserRuleCall_3() { return cPostreParserRuleCall_3; }
	}
	public class PrincipalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Principal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrincipalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Assignment cEnsaladaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cEnsaladaEnsaladaKeyword_3_0 = (Keyword)cEnsaladaAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cDescripcionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDescripcionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_6_0 = (RuleCall)cDescripcionAssignment_6.eContents().get(0);
		private final Keyword cFotoKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cFotoAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cFotoSTRINGTerminalRuleCall_8_0 = (RuleCall)cFotoAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cIngredientesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cIngredientesAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cIngredientesIngredienteCrossReference_9_1_0 = (CrossReference)cIngredientesAssignment_9_1.eContents().get(0);
		private final RuleCall cIngredientesIngredienteIDTerminalRuleCall_9_1_0_1 = (RuleCall)cIngredientesIngredienteCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_9_2 = (Group)cGroup_9.eContents().get(2);
		private final Keyword cCommaKeyword_9_2_0 = (Keyword)cGroup_9_2.eContents().get(0);
		private final Assignment cIngredientesAssignment_9_2_1 = (Assignment)cGroup_9_2.eContents().get(1);
		private final CrossReference cIngredientesIngredienteCrossReference_9_2_1_0 = (CrossReference)cIngredientesAssignment_9_2_1.eContents().get(0);
		private final RuleCall cIngredientesIngredienteIDTerminalRuleCall_9_2_1_0_1 = (RuleCall)cIngredientesIngredienteCrossReference_9_2_1_0.eContents().get(1);
		private final Keyword cSalsaRecomendadaKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cSalsaAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cSalsaSalsaRecomendadaEnumRuleCall_11_0 = (RuleCall)cSalsaAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cNutricionalKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cNutricionalAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cNutricionalNutricionalParserRuleCall_12_1_0 = (RuleCall)cNutricionalAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Principal:
		//	'Principal:' name=ID nombre=STRING ensalada?='ensalada'? '{'
		//	'Descripcion:' descripcion=STRING
		//	'Foto:' foto=STRING ('Ingredientes:' ingredientes+=[Ingrediente] (',' ingredientes+=[Ingrediente])*)?
		//	'Salsa recomendada:' salsa=SalsaRecomendada ('Nutricional' nutricional=Nutricional)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Principal:' name=ID nombre=STRING ensalada?='ensalada'? '{' 'Descripcion:' descripcion=STRING 'Foto:' foto=STRING
		//('Ingredientes:' ingredientes+=[Ingrediente] (',' ingredientes+=[Ingrediente])*)? 'Salsa recomendada:'
		//salsa=SalsaRecomendada ('Nutricional' nutricional=Nutricional)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Principal:'
		public Keyword getPrincipalKeyword_0() { return cPrincipalKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//ensalada?='ensalada'?
		public Assignment getEnsaladaAssignment_3() { return cEnsaladaAssignment_3; }
		
		//'ensalada'
		public Keyword getEnsaladaEnsaladaKeyword_3_0() { return cEnsaladaEnsaladaKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//'Descripcion:'
		public Keyword getDescripcionKeyword_5() { return cDescripcionKeyword_5; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_6() { return cDescripcionAssignment_6; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_6_0() { return cDescripcionSTRINGTerminalRuleCall_6_0; }
		
		//'Foto:'
		public Keyword getFotoKeyword_7() { return cFotoKeyword_7; }
		
		//foto=STRING
		public Assignment getFotoAssignment_8() { return cFotoAssignment_8; }
		
		//STRING
		public RuleCall getFotoSTRINGTerminalRuleCall_8_0() { return cFotoSTRINGTerminalRuleCall_8_0; }
		
		//('Ingredientes:' ingredientes+=[Ingrediente] (',' ingredientes+=[Ingrediente])*)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'Ingredientes:'
		public Keyword getIngredientesKeyword_9_0() { return cIngredientesKeyword_9_0; }
		
		//ingredientes+=[Ingrediente]
		public Assignment getIngredientesAssignment_9_1() { return cIngredientesAssignment_9_1; }
		
		//[Ingrediente]
		public CrossReference getIngredientesIngredienteCrossReference_9_1_0() { return cIngredientesIngredienteCrossReference_9_1_0; }
		
		//ID
		public RuleCall getIngredientesIngredienteIDTerminalRuleCall_9_1_0_1() { return cIngredientesIngredienteIDTerminalRuleCall_9_1_0_1; }
		
		//(',' ingredientes+=[Ingrediente])*
		public Group getGroup_9_2() { return cGroup_9_2; }
		
		//','
		public Keyword getCommaKeyword_9_2_0() { return cCommaKeyword_9_2_0; }
		
		//ingredientes+=[Ingrediente]
		public Assignment getIngredientesAssignment_9_2_1() { return cIngredientesAssignment_9_2_1; }
		
		//[Ingrediente]
		public CrossReference getIngredientesIngredienteCrossReference_9_2_1_0() { return cIngredientesIngredienteCrossReference_9_2_1_0; }
		
		//ID
		public RuleCall getIngredientesIngredienteIDTerminalRuleCall_9_2_1_0_1() { return cIngredientesIngredienteIDTerminalRuleCall_9_2_1_0_1; }
		
		//'Salsa recomendada:'
		public Keyword getSalsaRecomendadaKeyword_10() { return cSalsaRecomendadaKeyword_10; }
		
		//salsa=SalsaRecomendada
		public Assignment getSalsaAssignment_11() { return cSalsaAssignment_11; }
		
		//SalsaRecomendada
		public RuleCall getSalsaSalsaRecomendadaEnumRuleCall_11_0() { return cSalsaSalsaRecomendadaEnumRuleCall_11_0; }
		
		//('Nutricional' nutricional=Nutricional)?
		public Group getGroup_12() { return cGroup_12; }
		
		//'Nutricional'
		public Keyword getNutricionalKeyword_12_0() { return cNutricionalKeyword_12_0; }
		
		//nutricional=Nutricional
		public Assignment getNutricionalAssignment_12_1() { return cNutricionalAssignment_12_1; }
		
		//Nutricional
		public RuleCall getNutricionalNutricionalParserRuleCall_12_1_0() { return cNutricionalNutricionalParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class ComplementoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Complemento");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComplementoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cDescripcionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDescripcionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_5_0 = (RuleCall)cDescripcionAssignment_5.eContents().get(0);
		private final Keyword cFotoKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cFotoAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cFotoSTRINGTerminalRuleCall_7_0 = (RuleCall)cFotoAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cNutricionalKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cNutricionalAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cNutricionalNutricionalParserRuleCall_8_1_0 = (RuleCall)cNutricionalAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Complemento:
		//	'Complemento:' name=ID nombre=STRING '{'
		//	'Descripcion:' descripcion=STRING
		//	'Foto:' foto=STRING ('Nutricional' nutricional=Nutricional)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Complemento:' name=ID nombre=STRING '{' 'Descripcion:' descripcion=STRING 'Foto:' foto=STRING ('Nutricional'
		//nutricional=Nutricional)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Complemento:'
		public Keyword getComplementoKeyword_0() { return cComplementoKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'Descripcion:'
		public Keyword getDescripcionKeyword_4() { return cDescripcionKeyword_4; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_5() { return cDescripcionAssignment_5; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_5_0() { return cDescripcionSTRINGTerminalRuleCall_5_0; }
		
		//'Foto:'
		public Keyword getFotoKeyword_6() { return cFotoKeyword_6; }
		
		//foto=STRING
		public Assignment getFotoAssignment_7() { return cFotoAssignment_7; }
		
		//STRING
		public RuleCall getFotoSTRINGTerminalRuleCall_7_0() { return cFotoSTRINGTerminalRuleCall_7_0; }
		
		//('Nutricional' nutricional=Nutricional)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'Nutricional'
		public Keyword getNutricionalKeyword_8_0() { return cNutricionalKeyword_8_0; }
		
		//nutricional=Nutricional
		public Assignment getNutricionalAssignment_8_1() { return cNutricionalAssignment_8_1; }
		
		//Nutricional
		public RuleCall getNutricionalNutricionalParserRuleCall_8_1_0() { return cNutricionalNutricionalParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class BebidaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Bebida");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBebidaFriaParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBebidaCalienteParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Bebida:
		//	BebidaFria | BebidaCaliente;
		@Override public ParserRule getRule() { return rule; }
		
		//BebidaFria | BebidaCaliente
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BebidaFria
		public RuleCall getBebidaFriaParserRuleCall_0() { return cBebidaFriaParserRuleCall_0; }
		
		//BebidaCaliente
		public RuleCall getBebidaCalienteParserRuleCall_1() { return cBebidaCalienteParserRuleCall_1; }
	}
	public class BebidaFriaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.BebidaFria");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBebidaFriaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cDescripcionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDescripcionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_5_0 = (RuleCall)cDescripcionAssignment_5.eContents().get(0);
		private final Keyword cDistribuidorKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDistribuidorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDistribuidorDistribuidorEnumRuleCall_7_0 = (RuleCall)cDistribuidorAssignment_7.eContents().get(0);
		private final Keyword cFotoKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFotoAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFotoSTRINGTerminalRuleCall_9_0 = (RuleCall)cFotoAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cNutricionalKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cNutricionalAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cNutricionalNutricionalParserRuleCall_10_1_0 = (RuleCall)cNutricionalAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//BebidaFria:
		//	'Bebida fria:' name=ID nombre=STRING '{'
		//	'Descripcion:' descripcion=STRING
		//	'Distribuidor:' distribuidor=Distribuidor
		//	'Foto:' foto=STRING ('Nutricional' nutricional=Nutricional)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Bebida fria:' name=ID nombre=STRING '{' 'Descripcion:' descripcion=STRING 'Distribuidor:' distribuidor=Distribuidor
		//'Foto:' foto=STRING ('Nutricional' nutricional=Nutricional)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Bebida fria:'
		public Keyword getBebidaFriaKeyword_0() { return cBebidaFriaKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'Descripcion:'
		public Keyword getDescripcionKeyword_4() { return cDescripcionKeyword_4; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_5() { return cDescripcionAssignment_5; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_5_0() { return cDescripcionSTRINGTerminalRuleCall_5_0; }
		
		//'Distribuidor:'
		public Keyword getDistribuidorKeyword_6() { return cDistribuidorKeyword_6; }
		
		//distribuidor=Distribuidor
		public Assignment getDistribuidorAssignment_7() { return cDistribuidorAssignment_7; }
		
		//Distribuidor
		public RuleCall getDistribuidorDistribuidorEnumRuleCall_7_0() { return cDistribuidorDistribuidorEnumRuleCall_7_0; }
		
		//'Foto:'
		public Keyword getFotoKeyword_8() { return cFotoKeyword_8; }
		
		//foto=STRING
		public Assignment getFotoAssignment_9() { return cFotoAssignment_9; }
		
		//STRING
		public RuleCall getFotoSTRINGTerminalRuleCall_9_0() { return cFotoSTRINGTerminalRuleCall_9_0; }
		
		//('Nutricional' nutricional=Nutricional)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'Nutricional'
		public Keyword getNutricionalKeyword_10_0() { return cNutricionalKeyword_10_0; }
		
		//nutricional=Nutricional
		public Assignment getNutricionalAssignment_10_1() { return cNutricionalAssignment_10_1; }
		
		//Nutricional
		public RuleCall getNutricionalNutricionalParserRuleCall_10_1_0() { return cNutricionalNutricionalParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class BebidaCalienteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.BebidaCaliente");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBebidaCalienteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cDescripcionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDescripcionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_5_0 = (RuleCall)cDescripcionAssignment_5.eContents().get(0);
		private final Keyword cFotoKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cFotoAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cFotoSTRINGTerminalRuleCall_7_0 = (RuleCall)cFotoAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cNutricionalKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cNutricionalAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cNutricionalNutricionalParserRuleCall_8_1_0 = (RuleCall)cNutricionalAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//BebidaCaliente:
		//	'Bebida caliente:' name=ID nombre=STRING '{'
		//	'Descripcion:' descripcion=STRING
		//	'Foto:' foto=STRING ('Nutricional' nutricional=Nutricional)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Bebida caliente:' name=ID nombre=STRING '{' 'Descripcion:' descripcion=STRING 'Foto:' foto=STRING ('Nutricional'
		//nutricional=Nutricional)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Bebida caliente:'
		public Keyword getBebidaCalienteKeyword_0() { return cBebidaCalienteKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'Descripcion:'
		public Keyword getDescripcionKeyword_4() { return cDescripcionKeyword_4; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_5() { return cDescripcionAssignment_5; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_5_0() { return cDescripcionSTRINGTerminalRuleCall_5_0; }
		
		//'Foto:'
		public Keyword getFotoKeyword_6() { return cFotoKeyword_6; }
		
		//foto=STRING
		public Assignment getFotoAssignment_7() { return cFotoAssignment_7; }
		
		//STRING
		public RuleCall getFotoSTRINGTerminalRuleCall_7_0() { return cFotoSTRINGTerminalRuleCall_7_0; }
		
		//('Nutricional' nutricional=Nutricional)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'Nutricional'
		public Keyword getNutricionalKeyword_8_0() { return cNutricionalKeyword_8_0; }
		
		//nutricional=Nutricional
		public Assignment getNutricionalAssignment_8_1() { return cNutricionalAssignment_8_1; }
		
		//Nutricional
		public RuleCall getNutricionalNutricionalParserRuleCall_8_1_0() { return cNutricionalNutricionalParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class PostreElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Postre");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPostreKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Assignment cHeladoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cHeladoHeladoKeyword_3_0 = (Keyword)cHeladoAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cDescripcionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDescripcionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_6_0 = (RuleCall)cDescripcionAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDistribuidorKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDistribuidorAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cDistribuidorDistribuidorEnumRuleCall_7_1_0 = (RuleCall)cDistribuidorAssignment_7_1.eContents().get(0);
		private final Keyword cFotoKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFotoAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFotoSTRINGTerminalRuleCall_9_0 = (RuleCall)cFotoAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cIngredientesKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cIngredientesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cIngredientesIngredienteCrossReference_10_1_0 = (CrossReference)cIngredientesAssignment_10_1.eContents().get(0);
		private final RuleCall cIngredientesIngredienteIDTerminalRuleCall_10_1_0_1 = (RuleCall)cIngredientesIngredienteCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Keyword cCommaKeyword_10_2_0 = (Keyword)cGroup_10_2.eContents().get(0);
		private final Assignment cIngredientesAssignment_10_2_1 = (Assignment)cGroup_10_2.eContents().get(1);
		private final CrossReference cIngredientesIngredienteCrossReference_10_2_1_0 = (CrossReference)cIngredientesAssignment_10_2_1.eContents().get(0);
		private final RuleCall cIngredientesIngredienteIDTerminalRuleCall_10_2_1_0_1 = (RuleCall)cIngredientesIngredienteCrossReference_10_2_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cNutricionalKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cNutricionalAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cNutricionalNutricionalParserRuleCall_11_1_0 = (RuleCall)cNutricionalAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Postre:
		//	'Postre:' name=ID nombre=STRING helado?='helado'? '{'
		//	'Descripcion:' descripcion=STRING ('Distribuidor:' distribuidor=Distribuidor)?
		//	'Foto:' foto=STRING ('Ingredientes:' ingredientes+=[Ingrediente] (',' ingredientes+=[Ingrediente])*)? ('Nutricional'
		//	nutricional=Nutricional)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Postre:' name=ID nombre=STRING helado?='helado'? '{' 'Descripcion:' descripcion=STRING ('Distribuidor:'
		//distribuidor=Distribuidor)? 'Foto:' foto=STRING ('Ingredientes:' ingredientes+=[Ingrediente] (','
		//ingredientes+=[Ingrediente])*)? ('Nutricional' nutricional=Nutricional)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Postre:'
		public Keyword getPostreKeyword_0() { return cPostreKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//helado?='helado'?
		public Assignment getHeladoAssignment_3() { return cHeladoAssignment_3; }
		
		//'helado'
		public Keyword getHeladoHeladoKeyword_3_0() { return cHeladoHeladoKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//'Descripcion:'
		public Keyword getDescripcionKeyword_5() { return cDescripcionKeyword_5; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_6() { return cDescripcionAssignment_6; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_6_0() { return cDescripcionSTRINGTerminalRuleCall_6_0; }
		
		//('Distribuidor:' distribuidor=Distribuidor)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'Distribuidor:'
		public Keyword getDistribuidorKeyword_7_0() { return cDistribuidorKeyword_7_0; }
		
		//distribuidor=Distribuidor
		public Assignment getDistribuidorAssignment_7_1() { return cDistribuidorAssignment_7_1; }
		
		//Distribuidor
		public RuleCall getDistribuidorDistribuidorEnumRuleCall_7_1_0() { return cDistribuidorDistribuidorEnumRuleCall_7_1_0; }
		
		//'Foto:'
		public Keyword getFotoKeyword_8() { return cFotoKeyword_8; }
		
		//foto=STRING
		public Assignment getFotoAssignment_9() { return cFotoAssignment_9; }
		
		//STRING
		public RuleCall getFotoSTRINGTerminalRuleCall_9_0() { return cFotoSTRINGTerminalRuleCall_9_0; }
		
		//('Ingredientes:' ingredientes+=[Ingrediente] (',' ingredientes+=[Ingrediente])*)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'Ingredientes:'
		public Keyword getIngredientesKeyword_10_0() { return cIngredientesKeyword_10_0; }
		
		//ingredientes+=[Ingrediente]
		public Assignment getIngredientesAssignment_10_1() { return cIngredientesAssignment_10_1; }
		
		//[Ingrediente]
		public CrossReference getIngredientesIngredienteCrossReference_10_1_0() { return cIngredientesIngredienteCrossReference_10_1_0; }
		
		//ID
		public RuleCall getIngredientesIngredienteIDTerminalRuleCall_10_1_0_1() { return cIngredientesIngredienteIDTerminalRuleCall_10_1_0_1; }
		
		//(',' ingredientes+=[Ingrediente])*
		public Group getGroup_10_2() { return cGroup_10_2; }
		
		//','
		public Keyword getCommaKeyword_10_2_0() { return cCommaKeyword_10_2_0; }
		
		//ingredientes+=[Ingrediente]
		public Assignment getIngredientesAssignment_10_2_1() { return cIngredientesAssignment_10_2_1; }
		
		//[Ingrediente]
		public CrossReference getIngredientesIngredienteCrossReference_10_2_1_0() { return cIngredientesIngredienteCrossReference_10_2_1_0; }
		
		//ID
		public RuleCall getIngredientesIngredienteIDTerminalRuleCall_10_2_1_0_1() { return cIngredientesIngredienteIDTerminalRuleCall_10_2_1_0_1; }
		
		//('Nutricional' nutricional=Nutricional)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'Nutricional'
		public Keyword getNutricionalKeyword_11_0() { return cNutricionalKeyword_11_0; }
		
		//nutricional=Nutricional
		public Assignment getNutricionalAssignment_11_1() { return cNutricionalAssignment_11_1; }
		
		//Nutricional
		public RuleCall getNutricionalNutricionalParserRuleCall_11_1_0() { return cNutricionalNutricionalParserRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class NutricionalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Nutricional");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCantidadKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCantidadAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCantidadFloatParserRuleCall_2_0 = (RuleCall)cCantidadAssignment_2.eContents().get(0);
		private final Keyword cMedidaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUnidadAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUnidadSTRINGTerminalRuleCall_4_0 = (RuleCall)cUnidadAssignment_4.eContents().get(0);
		private final Keyword cEnergiaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEnergiaAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEnergiaFloatParserRuleCall_6_0 = (RuleCall)cEnergiaAssignment_6.eContents().get(0);
		private final Keyword cGrasasKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cGrasasAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cGrasasFloatParserRuleCall_8_0 = (RuleCall)cGrasasAssignment_8.eContents().get(0);
		private final Keyword cHidratosKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cHidratosAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cHidratosFloatParserRuleCall_10_0 = (RuleCall)cHidratosAssignment_10.eContents().get(0);
		private final Keyword cProteinasKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cProteinasAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cProteinasFloatParserRuleCall_12_0 = (RuleCall)cProteinasAssignment_12.eContents().get(0);
		private final Keyword cSalKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cSalAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cSalFloatParserRuleCall_14_0 = (RuleCall)cSalAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Nutricional:
		//	'{'
		//	'cantidad:' cantidad=Float
		//	'medida:' unidad=STRING
		//	'energia:' energia=Float
		//	'grasas:' grasas=Float
		//	'hidratos:' hidratos=Float
		//	'proteinas:' proteinas=Float
		//	'sal:' sal=Float
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{' 'cantidad:' cantidad=Float 'medida:' unidad=STRING 'energia:' energia=Float 'grasas:' grasas=Float 'hidratos:'
		//hidratos=Float 'proteinas:' proteinas=Float 'sal:' sal=Float '}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'cantidad:'
		public Keyword getCantidadKeyword_1() { return cCantidadKeyword_1; }
		
		//cantidad=Float
		public Assignment getCantidadAssignment_2() { return cCantidadAssignment_2; }
		
		//Float
		public RuleCall getCantidadFloatParserRuleCall_2_0() { return cCantidadFloatParserRuleCall_2_0; }
		
		//'medida:'
		public Keyword getMedidaKeyword_3() { return cMedidaKeyword_3; }
		
		//unidad=STRING
		public Assignment getUnidadAssignment_4() { return cUnidadAssignment_4; }
		
		//STRING
		public RuleCall getUnidadSTRINGTerminalRuleCall_4_0() { return cUnidadSTRINGTerminalRuleCall_4_0; }
		
		//'energia:'
		public Keyword getEnergiaKeyword_5() { return cEnergiaKeyword_5; }
		
		//energia=Float
		public Assignment getEnergiaAssignment_6() { return cEnergiaAssignment_6; }
		
		//Float
		public RuleCall getEnergiaFloatParserRuleCall_6_0() { return cEnergiaFloatParserRuleCall_6_0; }
		
		//'grasas:'
		public Keyword getGrasasKeyword_7() { return cGrasasKeyword_7; }
		
		//grasas=Float
		public Assignment getGrasasAssignment_8() { return cGrasasAssignment_8; }
		
		//Float
		public RuleCall getGrasasFloatParserRuleCall_8_0() { return cGrasasFloatParserRuleCall_8_0; }
		
		//'hidratos:'
		public Keyword getHidratosKeyword_9() { return cHidratosKeyword_9; }
		
		//hidratos=Float
		public Assignment getHidratosAssignment_10() { return cHidratosAssignment_10; }
		
		//Float
		public RuleCall getHidratosFloatParserRuleCall_10_0() { return cHidratosFloatParserRuleCall_10_0; }
		
		//'proteinas:'
		public Keyword getProteinasKeyword_11() { return cProteinasKeyword_11; }
		
		//proteinas=Float
		public Assignment getProteinasAssignment_12() { return cProteinasAssignment_12; }
		
		//Float
		public RuleCall getProteinasFloatParserRuleCall_12_0() { return cProteinasFloatParserRuleCall_12_0; }
		
		//'sal:'
		public Keyword getSalKeyword_13() { return cSalKeyword_13; }
		
		//sal=Float
		public Assignment getSalAssignment_14() { return cSalAssignment_14; }
		
		//Float
		public RuleCall getSalFloatParserRuleCall_14_0() { return cSalFloatParserRuleCall_14_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class MenuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Menu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMenuKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cDescripcionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDescripcionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_5_0 = (RuleCall)cDescripcionAssignment_5.eContents().get(0);
		private final Keyword cTamaOKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTamanioAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTamanioTamanioMenuEnumRuleCall_7_0 = (RuleCall)cTamanioAssignment_7.eContents().get(0);
		private final Keyword cFotoKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFotoAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFotoSTRINGTerminalRuleCall_9_0 = (RuleCall)cFotoAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cProductosKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cProductosAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cProductosProductoYParserRuleCall_10_1_0 = (RuleCall)cProductosAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Menu:
		//	'Menu:' name=ID nombre=STRING '{'
		//	'Descripcion:' descripcion=STRING
		//	'Tamaño:' tamanio=TamanioMenu
		//	'Foto:' foto=STRING ('Productos:' productos=ProductoY)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Menu:' name=ID nombre=STRING '{' 'Descripcion:' descripcion=STRING 'Tamaño:' tamanio=TamanioMenu 'Foto:' foto=STRING
		//('Productos:' productos=ProductoY)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Menu:'
		public Keyword getMenuKeyword_0() { return cMenuKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'Descripcion:'
		public Keyword getDescripcionKeyword_4() { return cDescripcionKeyword_4; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_5() { return cDescripcionAssignment_5; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_5_0() { return cDescripcionSTRINGTerminalRuleCall_5_0; }
		
		//'Tamaño:'
		public Keyword getTamaOKeyword_6() { return cTamaOKeyword_6; }
		
		//tamanio=TamanioMenu
		public Assignment getTamanioAssignment_7() { return cTamanioAssignment_7; }
		
		//TamanioMenu
		public RuleCall getTamanioTamanioMenuEnumRuleCall_7_0() { return cTamanioTamanioMenuEnumRuleCall_7_0; }
		
		//'Foto:'
		public Keyword getFotoKeyword_8() { return cFotoKeyword_8; }
		
		//foto=STRING
		public Assignment getFotoAssignment_9() { return cFotoAssignment_9; }
		
		//STRING
		public RuleCall getFotoSTRINGTerminalRuleCall_9_0() { return cFotoSTRINGTerminalRuleCall_9_0; }
		
		//('Productos:' productos=ProductoY)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'Productos:'
		public Keyword getProductosKeyword_10_0() { return cProductosKeyword_10_0; }
		
		//productos=ProductoY
		public Assignment getProductosAssignment_10_1() { return cProductosAssignment_10_1; }
		
		//ProductoY
		public RuleCall getProductosProductoYParserRuleCall_10_1_0() { return cProductosProductoYParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ProductoYElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.ProductoY");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIzqAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIzqProductoOParserRuleCall_0_0 = (RuleCall)cIzqAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cYKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDerAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDerProductoOParserRuleCall_1_1_0 = (RuleCall)cDerAssignment_1_1.eContents().get(0);
		
		//ProductoY:
		//	izq=ProductoO ('Y' der+=ProductoO)*;
		@Override public ParserRule getRule() { return rule; }
		
		//izq=ProductoO ('Y' der+=ProductoO)*
		public Group getGroup() { return cGroup; }
		
		//izq=ProductoO
		public Assignment getIzqAssignment_0() { return cIzqAssignment_0; }
		
		//ProductoO
		public RuleCall getIzqProductoOParserRuleCall_0_0() { return cIzqProductoOParserRuleCall_0_0; }
		
		//('Y' der+=ProductoO)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'Y'
		public Keyword getYKeyword_1_0() { return cYKeyword_1_0; }
		
		//der+=ProductoO
		public Assignment getDerAssignment_1_1() { return cDerAssignment_1_1; }
		
		//ProductoO
		public RuleCall getDerProductoOParserRuleCall_1_1_0() { return cDerProductoOParserRuleCall_1_1_0; }
	}
	public class ProductoOElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.ProductoO");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cIzqAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final CrossReference cIzqProductoCrossReference_0_0 = (CrossReference)cIzqAssignment_0.eContents().get(0);
		private final RuleCall cIzqProductoIDTerminalRuleCall_0_0_1 = (RuleCall)cIzqProductoCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cIzqAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cIzqProductoCrossReference_1_1_0 = (CrossReference)cIzqAssignment_1_1.eContents().get(0);
		private final RuleCall cIzqProductoIDTerminalRuleCall_1_1_0_1 = (RuleCall)cIzqProductoCrossReference_1_1_0.eContents().get(1);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cOKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cDerAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final CrossReference cDerProductoCrossReference_1_2_1_0 = (CrossReference)cDerAssignment_1_2_1.eContents().get(0);
		private final RuleCall cDerProductoIDTerminalRuleCall_1_2_1_0_1 = (RuleCall)cDerProductoCrossReference_1_2_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//ProductoO:
		//	izq=[Producto] | '(' izq=[Producto] ('O' der+=[Producto])* ')';
		@Override public ParserRule getRule() { return rule; }
		
		//izq=[Producto] | '(' izq=[Producto] ('O' der+=[Producto])* ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//izq=[Producto]
		public Assignment getIzqAssignment_0() { return cIzqAssignment_0; }
		
		//[Producto]
		public CrossReference getIzqProductoCrossReference_0_0() { return cIzqProductoCrossReference_0_0; }
		
		//ID
		public RuleCall getIzqProductoIDTerminalRuleCall_0_0_1() { return cIzqProductoIDTerminalRuleCall_0_0_1; }
		
		//'(' izq=[Producto] ('O' der+=[Producto])* ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//izq=[Producto]
		public Assignment getIzqAssignment_1_1() { return cIzqAssignment_1_1; }
		
		//[Producto]
		public CrossReference getIzqProductoCrossReference_1_1_0() { return cIzqProductoCrossReference_1_1_0; }
		
		//ID
		public RuleCall getIzqProductoIDTerminalRuleCall_1_1_0_1() { return cIzqProductoIDTerminalRuleCall_1_1_0_1; }
		
		//('O' der+=[Producto])*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//'O'
		public Keyword getOKeyword_1_2_0() { return cOKeyword_1_2_0; }
		
		//der+=[Producto]
		public Assignment getDerAssignment_1_2_1() { return cDerAssignment_1_2_1; }
		
		//[Producto]
		public CrossReference getDerProductoCrossReference_1_2_1_0() { return cDerProductoCrossReference_1_2_1_0; }
		
		//ID
		public RuleCall getDerProductoIDTerminalRuleCall_1_2_1_0_1() { return cDerProductoIDTerminalRuleCall_1_2_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
	}
	public class FloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Float");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//Float:
		//	INT (',' INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//INT (',' INT)?
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//(',' INT)?
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_1() { return cINTTerminalRuleCall_1_1; }
	}
	
	public class SalsaRecomendadaElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.SalsaRecomendada");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNINGUNAEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNINGUNANINGUNAKeyword_0_0 = (Keyword)cNINGUNAEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cACEITE_Y_VINAGREEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cACEITE_Y_VINAGREACEITE_Y_VINAGREKeyword_1_0 = (Keyword)cACEITE_Y_VINAGREEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCESAREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCESARCESARKeyword_2_0 = (Keyword)cCESAREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMODENAEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMODENAMODENAKeyword_3_0 = (Keyword)cMODENAEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cMOSTAZAEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cMOSTAZAMOSTAZAKeyword_4_0 = (Keyword)cMOSTAZAEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum SalsaRecomendada:
		//	NINGUNA | ACEITE_Y_VINAGRE | CESAR | MODENA | MOSTAZA;
		public EnumRule getRule() { return rule; }
		
		//NINGUNA | ACEITE_Y_VINAGRE | CESAR | MODENA | MOSTAZA
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NINGUNA
		public EnumLiteralDeclaration getNINGUNAEnumLiteralDeclaration_0() { return cNINGUNAEnumLiteralDeclaration_0; }
		
		//"NINGUNA"
		public Keyword getNINGUNANINGUNAKeyword_0_0() { return cNINGUNANINGUNAKeyword_0_0; }
		
		//ACEITE_Y_VINAGRE
		public EnumLiteralDeclaration getACEITE_Y_VINAGREEnumLiteralDeclaration_1() { return cACEITE_Y_VINAGREEnumLiteralDeclaration_1; }
		
		//"ACEITE_Y_VINAGRE"
		public Keyword getACEITE_Y_VINAGREACEITE_Y_VINAGREKeyword_1_0() { return cACEITE_Y_VINAGREACEITE_Y_VINAGREKeyword_1_0; }
		
		//CESAR
		public EnumLiteralDeclaration getCESAREnumLiteralDeclaration_2() { return cCESAREnumLiteralDeclaration_2; }
		
		//"CESAR"
		public Keyword getCESARCESARKeyword_2_0() { return cCESARCESARKeyword_2_0; }
		
		//MODENA
		public EnumLiteralDeclaration getMODENAEnumLiteralDeclaration_3() { return cMODENAEnumLiteralDeclaration_3; }
		
		//"MODENA"
		public Keyword getMODENAMODENAKeyword_3_0() { return cMODENAMODENAKeyword_3_0; }
		
		//MOSTAZA
		public EnumLiteralDeclaration getMOSTAZAEnumLiteralDeclaration_4() { return cMOSTAZAEnumLiteralDeclaration_4; }
		
		//"MOSTAZA"
		public Keyword getMOSTAZAMOSTAZAKeyword_4_0() { return cMOSTAZAMOSTAZAKeyword_4_0; }
	}
	public class TamanioMenuElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.TamanioMenu");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNORMALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNORMALNORMALKeyword_0_0 = (Keyword)cNORMALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGRANDEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGRANDEGRANDEKeyword_1_0 = (Keyword)cGRANDEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNORMAL_Y_GRANDEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNORMAL_Y_GRANDENORMAL_Y_GRANDEKeyword_2_0 = (Keyword)cNORMAL_Y_GRANDEEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TamanioMenu:
		//	NORMAL | GRANDE | NORMAL_Y_GRANDE;
		public EnumRule getRule() { return rule; }
		
		//NORMAL | GRANDE | NORMAL_Y_GRANDE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NORMAL
		public EnumLiteralDeclaration getNORMALEnumLiteralDeclaration_0() { return cNORMALEnumLiteralDeclaration_0; }
		
		//"NORMAL"
		public Keyword getNORMALNORMALKeyword_0_0() { return cNORMALNORMALKeyword_0_0; }
		
		//GRANDE
		public EnumLiteralDeclaration getGRANDEEnumLiteralDeclaration_1() { return cGRANDEEnumLiteralDeclaration_1; }
		
		//"GRANDE"
		public Keyword getGRANDEGRANDEKeyword_1_0() { return cGRANDEGRANDEKeyword_1_0; }
		
		//NORMAL_Y_GRANDE
		public EnumLiteralDeclaration getNORMAL_Y_GRANDEEnumLiteralDeclaration_2() { return cNORMAL_Y_GRANDEEnumLiteralDeclaration_2; }
		
		//"NORMAL_Y_GRANDE"
		public Keyword getNORMAL_Y_GRANDENORMAL_Y_GRANDEKeyword_2_0() { return cNORMAL_Y_GRANDENORMAL_Y_GRANDEKeyword_2_0; }
	}
	public class DistribuidorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.Distribuidor");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCOCA_COLAEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCOCA_COLACOCA_COLAKeyword_0_0 = (Keyword)cCOCA_COLAEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAQUABONAEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAQUABONAAQUABONAKeyword_1_0 = (Keyword)cAQUABONAEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMAHOUEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMAHOUMAHOUKeyword_2_0 = (Keyword)cMAHOUEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cALVALLEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cALVALLEALVALLEKeyword_3_0 = (Keyword)cALVALLEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cTROPICANAEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cTROPICANATROPICANAKeyword_4_0 = (Keyword)cTROPICANAEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cOREOEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cOREOOREOKeyword_5_0 = (Keyword)cOREOEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cMILKAEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cMILKAMILKAKeyword_6_0 = (Keyword)cMILKAEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cDANONEEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cDANONEDANONEKeyword_7_0 = (Keyword)cDANONEEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum Distribuidor:
		//	COCA_COLA | AQUABONA | MAHOU | ALVALLE | TROPICANA | OREO | MILKA | DANONE;
		public EnumRule getRule() { return rule; }
		
		//COCA_COLA | AQUABONA | MAHOU | ALVALLE | TROPICANA | OREO | MILKA | DANONE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//COCA_COLA
		public EnumLiteralDeclaration getCOCA_COLAEnumLiteralDeclaration_0() { return cCOCA_COLAEnumLiteralDeclaration_0; }
		
		//"COCA_COLA"
		public Keyword getCOCA_COLACOCA_COLAKeyword_0_0() { return cCOCA_COLACOCA_COLAKeyword_0_0; }
		
		//AQUABONA
		public EnumLiteralDeclaration getAQUABONAEnumLiteralDeclaration_1() { return cAQUABONAEnumLiteralDeclaration_1; }
		
		//"AQUABONA"
		public Keyword getAQUABONAAQUABONAKeyword_1_0() { return cAQUABONAAQUABONAKeyword_1_0; }
		
		//MAHOU
		public EnumLiteralDeclaration getMAHOUEnumLiteralDeclaration_2() { return cMAHOUEnumLiteralDeclaration_2; }
		
		//"MAHOU"
		public Keyword getMAHOUMAHOUKeyword_2_0() { return cMAHOUMAHOUKeyword_2_0; }
		
		//ALVALLE
		public EnumLiteralDeclaration getALVALLEEnumLiteralDeclaration_3() { return cALVALLEEnumLiteralDeclaration_3; }
		
		//"ALVALLE"
		public Keyword getALVALLEALVALLEKeyword_3_0() { return cALVALLEALVALLEKeyword_3_0; }
		
		//TROPICANA
		public EnumLiteralDeclaration getTROPICANAEnumLiteralDeclaration_4() { return cTROPICANAEnumLiteralDeclaration_4; }
		
		//"TROPICANA"
		public Keyword getTROPICANATROPICANAKeyword_4_0() { return cTROPICANATROPICANAKeyword_4_0; }
		
		//OREO
		public EnumLiteralDeclaration getOREOEnumLiteralDeclaration_5() { return cOREOEnumLiteralDeclaration_5; }
		
		//"OREO"
		public Keyword getOREOOREOKeyword_5_0() { return cOREOOREOKeyword_5_0; }
		
		//MILKA
		public EnumLiteralDeclaration getMILKAEnumLiteralDeclaration_6() { return cMILKAEnumLiteralDeclaration_6; }
		
		//"MILKA"
		public Keyword getMILKAMILKAKeyword_6_0() { return cMILKAMILKAKeyword_6_0; }
		
		//DANONE
		public EnumLiteralDeclaration getDANONEEnumLiteralDeclaration_7() { return cDANONEEnumLiteralDeclaration_7; }
		
		//"DANONE"
		public Keyword getDANONEDANONEKeyword_7_0() { return cDANONEDANONEKeyword_7_0; }
	}
	
	private final RestauranteElements pRestaurante;
	private final IngredienteElements pIngrediente;
	private final ProductoElements pProducto;
	private final PrincipalElements pPrincipal;
	private final ComplementoElements pComplemento;
	private final BebidaElements pBebida;
	private final BebidaFriaElements pBebidaFria;
	private final BebidaCalienteElements pBebidaCaliente;
	private final PostreElements pPostre;
	private final NutricionalElements pNutricional;
	private final MenuElements pMenu;
	private final ProductoYElements pProductoY;
	private final ProductoOElements pProductoO;
	private final FloatElements pFloat;
	private final SalsaRecomendadaElements eSalsaRecomendada;
	private final TamanioMenuElements eTamanioMenu;
	private final DistribuidorElements eDistribuidor;
	private final TerminalRule tFECHA;
	private final TerminalRule tURL;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RestauranteGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRestaurante = new RestauranteElements();
		this.pIngrediente = new IngredienteElements();
		this.pProducto = new ProductoElements();
		this.pPrincipal = new PrincipalElements();
		this.pComplemento = new ComplementoElements();
		this.pBebida = new BebidaElements();
		this.pBebidaFria = new BebidaFriaElements();
		this.pBebidaCaliente = new BebidaCalienteElements();
		this.pPostre = new PostreElements();
		this.pNutricional = new NutricionalElements();
		this.pMenu = new MenuElements();
		this.pProductoY = new ProductoYElements();
		this.pProductoO = new ProductoOElements();
		this.pFloat = new FloatElements();
		this.eSalsaRecomendada = new SalsaRecomendadaElements();
		this.eTamanioMenu = new TamanioMenuElements();
		this.eDistribuidor = new DistribuidorElements();
		this.tFECHA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.FECHA");
		this.tURL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.restaurante.Restaurante.URL");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.dsl.restaurante.Restaurante".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Restaurante:
	//	'Restaurantes' nombre=STRING
	//	'fecha' fecha=FECHA
	//	'Ingredientes' '{'
	//	ingredientes+=Ingrediente*
	//	'}'
	//	'Productos' '{'
	//	productos+=Producto*
	//	'}'
	//	'Menus' '{'
	//	menus+=Menu*
	//	'}';
	public RestauranteElements getRestauranteAccess() {
		return pRestaurante;
	}
	
	public ParserRule getRestauranteRule() {
		return getRestauranteAccess().getRule();
	}
	
	//Ingrediente:
	//	'Ingrediente:' name=ID
	//	nombre=STRING ('infoURL:' infoURL=URL)? ('foto:' foto=STRING)?
	//	alergenico?='alergenico'?;
	public IngredienteElements getIngredienteAccess() {
		return pIngrediente;
	}
	
	public ParserRule getIngredienteRule() {
		return getIngredienteAccess().getRule();
	}
	
	//Producto:
	//	Principal | Complemento | Bebida | Postre;
	public ProductoElements getProductoAccess() {
		return pProducto;
	}
	
	public ParserRule getProductoRule() {
		return getProductoAccess().getRule();
	}
	
	//Principal:
	//	'Principal:' name=ID nombre=STRING ensalada?='ensalada'? '{'
	//	'Descripcion:' descripcion=STRING
	//	'Foto:' foto=STRING ('Ingredientes:' ingredientes+=[Ingrediente] (',' ingredientes+=[Ingrediente])*)?
	//	'Salsa recomendada:' salsa=SalsaRecomendada ('Nutricional' nutricional=Nutricional)?
	//	'}';
	public PrincipalElements getPrincipalAccess() {
		return pPrincipal;
	}
	
	public ParserRule getPrincipalRule() {
		return getPrincipalAccess().getRule();
	}
	
	//Complemento:
	//	'Complemento:' name=ID nombre=STRING '{'
	//	'Descripcion:' descripcion=STRING
	//	'Foto:' foto=STRING ('Nutricional' nutricional=Nutricional)?
	//	'}';
	public ComplementoElements getComplementoAccess() {
		return pComplemento;
	}
	
	public ParserRule getComplementoRule() {
		return getComplementoAccess().getRule();
	}
	
	//Bebida:
	//	BebidaFria | BebidaCaliente;
	public BebidaElements getBebidaAccess() {
		return pBebida;
	}
	
	public ParserRule getBebidaRule() {
		return getBebidaAccess().getRule();
	}
	
	//BebidaFria:
	//	'Bebida fria:' name=ID nombre=STRING '{'
	//	'Descripcion:' descripcion=STRING
	//	'Distribuidor:' distribuidor=Distribuidor
	//	'Foto:' foto=STRING ('Nutricional' nutricional=Nutricional)?
	//	'}';
	public BebidaFriaElements getBebidaFriaAccess() {
		return pBebidaFria;
	}
	
	public ParserRule getBebidaFriaRule() {
		return getBebidaFriaAccess().getRule();
	}
	
	//BebidaCaliente:
	//	'Bebida caliente:' name=ID nombre=STRING '{'
	//	'Descripcion:' descripcion=STRING
	//	'Foto:' foto=STRING ('Nutricional' nutricional=Nutricional)?
	//	'}';
	public BebidaCalienteElements getBebidaCalienteAccess() {
		return pBebidaCaliente;
	}
	
	public ParserRule getBebidaCalienteRule() {
		return getBebidaCalienteAccess().getRule();
	}
	
	//Postre:
	//	'Postre:' name=ID nombre=STRING helado?='helado'? '{'
	//	'Descripcion:' descripcion=STRING ('Distribuidor:' distribuidor=Distribuidor)?
	//	'Foto:' foto=STRING ('Ingredientes:' ingredientes+=[Ingrediente] (',' ingredientes+=[Ingrediente])*)? ('Nutricional'
	//	nutricional=Nutricional)?
	//	'}';
	public PostreElements getPostreAccess() {
		return pPostre;
	}
	
	public ParserRule getPostreRule() {
		return getPostreAccess().getRule();
	}
	
	//Nutricional:
	//	'{'
	//	'cantidad:' cantidad=Float
	//	'medida:' unidad=STRING
	//	'energia:' energia=Float
	//	'grasas:' grasas=Float
	//	'hidratos:' hidratos=Float
	//	'proteinas:' proteinas=Float
	//	'sal:' sal=Float
	//	'}';
	public NutricionalElements getNutricionalAccess() {
		return pNutricional;
	}
	
	public ParserRule getNutricionalRule() {
		return getNutricionalAccess().getRule();
	}
	
	//Menu:
	//	'Menu:' name=ID nombre=STRING '{'
	//	'Descripcion:' descripcion=STRING
	//	'Tamaño:' tamanio=TamanioMenu
	//	'Foto:' foto=STRING ('Productos:' productos=ProductoY)?
	//	'}';
	public MenuElements getMenuAccess() {
		return pMenu;
	}
	
	public ParserRule getMenuRule() {
		return getMenuAccess().getRule();
	}
	
	//ProductoY:
	//	izq=ProductoO ('Y' der+=ProductoO)*;
	public ProductoYElements getProductoYAccess() {
		return pProductoY;
	}
	
	public ParserRule getProductoYRule() {
		return getProductoYAccess().getRule();
	}
	
	//ProductoO:
	//	izq=[Producto] | '(' izq=[Producto] ('O' der+=[Producto])* ')';
	public ProductoOElements getProductoOAccess() {
		return pProductoO;
	}
	
	public ParserRule getProductoORule() {
		return getProductoOAccess().getRule();
	}
	
	//Float:
	//	INT (',' INT)?;
	public FloatElements getFloatAccess() {
		return pFloat;
	}
	
	public ParserRule getFloatRule() {
		return getFloatAccess().getRule();
	}
	
	//enum SalsaRecomendada:
	//	NINGUNA | ACEITE_Y_VINAGRE | CESAR | MODENA | MOSTAZA;
	public SalsaRecomendadaElements getSalsaRecomendadaAccess() {
		return eSalsaRecomendada;
	}
	
	public EnumRule getSalsaRecomendadaRule() {
		return getSalsaRecomendadaAccess().getRule();
	}
	
	//enum TamanioMenu:
	//	NORMAL | GRANDE | NORMAL_Y_GRANDE;
	public TamanioMenuElements getTamanioMenuAccess() {
		return eTamanioMenu;
	}
	
	public EnumRule getTamanioMenuRule() {
		return getTamanioMenuAccess().getRule();
	}
	
	//enum Distribuidor:
	//	COCA_COLA | AQUABONA | MAHOU | ALVALLE | TROPICANA | OREO | MILKA | DANONE;
	public DistribuidorElements getDistribuidorAccess() {
		return eDistribuidor;
	}
	
	public EnumRule getDistribuidorRule() {
		return getDistribuidorAccess().getRule();
	}
	
	//terminal FECHA:
	//	'0'..'9' '0'..'9' '-'
	//	'0'..'9' '0'..'9' '-'
	//	'0'..'9' '0'..'9' '0'..'9' '0'..'9';
	public TerminalRule getFECHARule() {
		return tFECHA;
	}
	
	//terminal URL:
	//	('http' | 'https') '://' ('a'..'z' | 'A'..'Z' | '_' | '-' | '(' | ')' | '\\' | '/' | '.' | '0'..'9')+;
	public TerminalRule getURLRule() {
		return tURL;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
