/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.web;

import org.xtext.dsl.restaurante.web.AbstractRestauranteWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class RestauranteWebModule extends AbstractRestauranteWebModule {
}
