/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.dsl.restaurante.restaurante.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage
 * @generated
 */
public class RestauranteSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static RestaurantePackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RestauranteSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = RestaurantePackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case RestaurantePackage.RESTAURANTE:
      {
        Restaurante restaurante = (Restaurante)theEObject;
        T result = caseRestaurante(restaurante);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.INGREDIENTE:
      {
        Ingrediente ingrediente = (Ingrediente)theEObject;
        T result = caseIngrediente(ingrediente);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.PRODUCTO:
      {
        Producto producto = (Producto)theEObject;
        T result = caseProducto(producto);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.PRINCIPAL:
      {
        Principal principal = (Principal)theEObject;
        T result = casePrincipal(principal);
        if (result == null) result = caseProducto(principal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.COMPLEMENTO:
      {
        Complemento complemento = (Complemento)theEObject;
        T result = caseComplemento(complemento);
        if (result == null) result = caseProducto(complemento);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.BEBIDA:
      {
        Bebida bebida = (Bebida)theEObject;
        T result = caseBebida(bebida);
        if (result == null) result = caseProducto(bebida);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.BEBIDA_FRIA:
      {
        BebidaFria bebidaFria = (BebidaFria)theEObject;
        T result = caseBebidaFria(bebidaFria);
        if (result == null) result = caseBebida(bebidaFria);
        if (result == null) result = caseProducto(bebidaFria);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.BEBIDA_CALIENTE:
      {
        BebidaCaliente bebidaCaliente = (BebidaCaliente)theEObject;
        T result = caseBebidaCaliente(bebidaCaliente);
        if (result == null) result = caseBebida(bebidaCaliente);
        if (result == null) result = caseProducto(bebidaCaliente);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.POSTRE:
      {
        Postre postre = (Postre)theEObject;
        T result = casePostre(postre);
        if (result == null) result = caseProducto(postre);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.NUTRICIONAL:
      {
        Nutricional nutricional = (Nutricional)theEObject;
        T result = caseNutricional(nutricional);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.MENU:
      {
        Menu menu = (Menu)theEObject;
        T result = caseMenu(menu);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.PRODUCTO_Y:
      {
        ProductoY productoY = (ProductoY)theEObject;
        T result = caseProductoY(productoY);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case RestaurantePackage.PRODUCTO_O:
      {
        ProductoO productoO = (ProductoO)theEObject;
        T result = caseProductoO(productoO);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Restaurante</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Restaurante</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRestaurante(Restaurante object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ingrediente</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ingrediente</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIngrediente(Ingrediente object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Producto</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Producto</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProducto(Producto object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Principal</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Principal</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePrincipal(Principal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Complemento</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Complemento</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComplemento(Complemento object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Bebida</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Bebida</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBebida(Bebida object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Bebida Fria</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Bebida Fria</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBebidaFria(BebidaFria object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Bebida Caliente</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Bebida Caliente</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBebidaCaliente(BebidaCaliente object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Postre</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Postre</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePostre(Postre object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Nutricional</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Nutricional</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNutricional(Nutricional object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Menu</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Menu</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMenu(Menu object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Producto Y</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Producto Y</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProductoY(ProductoY object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Producto O</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Producto O</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProductoO(ProductoO object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //RestauranteSwitch
