/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRestauranteScopeProvider extends DelegatingScopeProvider {
}
