/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class RestauranteProjectInfo extends DefaultProjectInfo {

}
