/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class RestauranteWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public RestauranteWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
