/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.ui.wizard;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.resource.FileExtensionProvider;

@SuppressWarnings("all")
public class RestauranteNewProjectWizardInitialContents {
  @Inject
  private FileExtensionProvider fileExtensionProvider;
  
  public void generateInitialContents(final IFileSystemAccess2 fsa) {
    String _primaryFileExtension = this.fileExtensionProvider.getPrimaryFileExtension();
    String _plus = ("src/model/Model." + _primaryFileExtension);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("Restaurantes \"Hola\" fecha 30-10-2016");
    _builder.newLine();
    _builder.newLine();
    _builder.append("Ingredientes {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Ingrediente: COD1 \'moluscos\' infoURL: http://moluscos.com alergenico");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus, _builder);
  }
}
