/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.dsl.restaurante.ide.contentassist.antlr.internal.InternalRestauranteParser;
import org.xtext.dsl.restaurante.services.RestauranteGrammarAccess;

public class RestauranteParser extends AbstractContentAssistParser {

	@Inject
	private RestauranteGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalRestauranteParser createParser() {
		InternalRestauranteParser result = new InternalRestauranteParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProductoAccess().getAlternatives(), "rule__Producto__Alternatives");
					put(grammarAccess.getBebidaAccess().getAlternatives(), "rule__Bebida__Alternatives");
					put(grammarAccess.getProductoOAccess().getAlternatives(), "rule__ProductoO__Alternatives");
					put(grammarAccess.getSalsaRecomendadaAccess().getAlternatives(), "rule__SalsaRecomendada__Alternatives");
					put(grammarAccess.getTamanioMenuAccess().getAlternatives(), "rule__TamanioMenu__Alternatives");
					put(grammarAccess.getDistribuidorAccess().getAlternatives(), "rule__Distribuidor__Alternatives");
					put(grammarAccess.getRestauranteAccess().getGroup(), "rule__Restaurante__Group__0");
					put(grammarAccess.getIngredienteAccess().getGroup(), "rule__Ingrediente__Group__0");
					put(grammarAccess.getIngredienteAccess().getGroup_3(), "rule__Ingrediente__Group_3__0");
					put(grammarAccess.getIngredienteAccess().getGroup_4(), "rule__Ingrediente__Group_4__0");
					put(grammarAccess.getPrincipalAccess().getGroup(), "rule__Principal__Group__0");
					put(grammarAccess.getPrincipalAccess().getGroup_9(), "rule__Principal__Group_9__0");
					put(grammarAccess.getPrincipalAccess().getGroup_9_2(), "rule__Principal__Group_9_2__0");
					put(grammarAccess.getPrincipalAccess().getGroup_12(), "rule__Principal__Group_12__0");
					put(grammarAccess.getComplementoAccess().getGroup(), "rule__Complemento__Group__0");
					put(grammarAccess.getComplementoAccess().getGroup_8(), "rule__Complemento__Group_8__0");
					put(grammarAccess.getBebidaFriaAccess().getGroup(), "rule__BebidaFria__Group__0");
					put(grammarAccess.getBebidaFriaAccess().getGroup_10(), "rule__BebidaFria__Group_10__0");
					put(grammarAccess.getBebidaCalienteAccess().getGroup(), "rule__BebidaCaliente__Group__0");
					put(grammarAccess.getBebidaCalienteAccess().getGroup_8(), "rule__BebidaCaliente__Group_8__0");
					put(grammarAccess.getPostreAccess().getGroup(), "rule__Postre__Group__0");
					put(grammarAccess.getPostreAccess().getGroup_7(), "rule__Postre__Group_7__0");
					put(grammarAccess.getPostreAccess().getGroup_10(), "rule__Postre__Group_10__0");
					put(grammarAccess.getPostreAccess().getGroup_10_2(), "rule__Postre__Group_10_2__0");
					put(grammarAccess.getPostreAccess().getGroup_11(), "rule__Postre__Group_11__0");
					put(grammarAccess.getNutricionalAccess().getGroup(), "rule__Nutricional__Group__0");
					put(grammarAccess.getMenuAccess().getGroup(), "rule__Menu__Group__0");
					put(grammarAccess.getMenuAccess().getGroup_10(), "rule__Menu__Group_10__0");
					put(grammarAccess.getProductoYAccess().getGroup(), "rule__ProductoY__Group__0");
					put(grammarAccess.getProductoYAccess().getGroup_1(), "rule__ProductoY__Group_1__0");
					put(grammarAccess.getProductoOAccess().getGroup_1(), "rule__ProductoO__Group_1__0");
					put(grammarAccess.getProductoOAccess().getGroup_1_2(), "rule__ProductoO__Group_1_2__0");
					put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
					put(grammarAccess.getFloatAccess().getGroup_1(), "rule__Float__Group_1__0");
					put(grammarAccess.getRestauranteAccess().getNombreAssignment_1(), "rule__Restaurante__NombreAssignment_1");
					put(grammarAccess.getRestauranteAccess().getFechaAssignment_3(), "rule__Restaurante__FechaAssignment_3");
					put(grammarAccess.getRestauranteAccess().getIngredientesAssignment_6(), "rule__Restaurante__IngredientesAssignment_6");
					put(grammarAccess.getRestauranteAccess().getProductosAssignment_10(), "rule__Restaurante__ProductosAssignment_10");
					put(grammarAccess.getRestauranteAccess().getMenusAssignment_14(), "rule__Restaurante__MenusAssignment_14");
					put(grammarAccess.getIngredienteAccess().getNameAssignment_1(), "rule__Ingrediente__NameAssignment_1");
					put(grammarAccess.getIngredienteAccess().getNombreAssignment_2(), "rule__Ingrediente__NombreAssignment_2");
					put(grammarAccess.getIngredienteAccess().getInfoURLAssignment_3_1(), "rule__Ingrediente__InfoURLAssignment_3_1");
					put(grammarAccess.getIngredienteAccess().getFotoAssignment_4_1(), "rule__Ingrediente__FotoAssignment_4_1");
					put(grammarAccess.getIngredienteAccess().getAlergenicoAssignment_5(), "rule__Ingrediente__AlergenicoAssignment_5");
					put(grammarAccess.getPrincipalAccess().getNameAssignment_1(), "rule__Principal__NameAssignment_1");
					put(grammarAccess.getPrincipalAccess().getNombreAssignment_2(), "rule__Principal__NombreAssignment_2");
					put(grammarAccess.getPrincipalAccess().getEnsaladaAssignment_3(), "rule__Principal__EnsaladaAssignment_3");
					put(grammarAccess.getPrincipalAccess().getDescripcionAssignment_6(), "rule__Principal__DescripcionAssignment_6");
					put(grammarAccess.getPrincipalAccess().getFotoAssignment_8(), "rule__Principal__FotoAssignment_8");
					put(grammarAccess.getPrincipalAccess().getIngredientesAssignment_9_1(), "rule__Principal__IngredientesAssignment_9_1");
					put(grammarAccess.getPrincipalAccess().getIngredientesAssignment_9_2_1(), "rule__Principal__IngredientesAssignment_9_2_1");
					put(grammarAccess.getPrincipalAccess().getSalsaAssignment_11(), "rule__Principal__SalsaAssignment_11");
					put(grammarAccess.getPrincipalAccess().getNutricionalAssignment_12_1(), "rule__Principal__NutricionalAssignment_12_1");
					put(grammarAccess.getComplementoAccess().getNameAssignment_1(), "rule__Complemento__NameAssignment_1");
					put(grammarAccess.getComplementoAccess().getNombreAssignment_2(), "rule__Complemento__NombreAssignment_2");
					put(grammarAccess.getComplementoAccess().getDescripcionAssignment_5(), "rule__Complemento__DescripcionAssignment_5");
					put(grammarAccess.getComplementoAccess().getFotoAssignment_7(), "rule__Complemento__FotoAssignment_7");
					put(grammarAccess.getComplementoAccess().getNutricionalAssignment_8_1(), "rule__Complemento__NutricionalAssignment_8_1");
					put(grammarAccess.getBebidaFriaAccess().getNameAssignment_1(), "rule__BebidaFria__NameAssignment_1");
					put(grammarAccess.getBebidaFriaAccess().getNombreAssignment_2(), "rule__BebidaFria__NombreAssignment_2");
					put(grammarAccess.getBebidaFriaAccess().getDescripcionAssignment_5(), "rule__BebidaFria__DescripcionAssignment_5");
					put(grammarAccess.getBebidaFriaAccess().getDistribuidorAssignment_7(), "rule__BebidaFria__DistribuidorAssignment_7");
					put(grammarAccess.getBebidaFriaAccess().getFotoAssignment_9(), "rule__BebidaFria__FotoAssignment_9");
					put(grammarAccess.getBebidaFriaAccess().getNutricionalAssignment_10_1(), "rule__BebidaFria__NutricionalAssignment_10_1");
					put(grammarAccess.getBebidaCalienteAccess().getNameAssignment_1(), "rule__BebidaCaliente__NameAssignment_1");
					put(grammarAccess.getBebidaCalienteAccess().getNombreAssignment_2(), "rule__BebidaCaliente__NombreAssignment_2");
					put(grammarAccess.getBebidaCalienteAccess().getDescripcionAssignment_5(), "rule__BebidaCaliente__DescripcionAssignment_5");
					put(grammarAccess.getBebidaCalienteAccess().getFotoAssignment_7(), "rule__BebidaCaliente__FotoAssignment_7");
					put(grammarAccess.getBebidaCalienteAccess().getNutricionalAssignment_8_1(), "rule__BebidaCaliente__NutricionalAssignment_8_1");
					put(grammarAccess.getPostreAccess().getNameAssignment_1(), "rule__Postre__NameAssignment_1");
					put(grammarAccess.getPostreAccess().getNombreAssignment_2(), "rule__Postre__NombreAssignment_2");
					put(grammarAccess.getPostreAccess().getHeladoAssignment_3(), "rule__Postre__HeladoAssignment_3");
					put(grammarAccess.getPostreAccess().getDescripcionAssignment_6(), "rule__Postre__DescripcionAssignment_6");
					put(grammarAccess.getPostreAccess().getDistribuidorAssignment_7_1(), "rule__Postre__DistribuidorAssignment_7_1");
					put(grammarAccess.getPostreAccess().getFotoAssignment_9(), "rule__Postre__FotoAssignment_9");
					put(grammarAccess.getPostreAccess().getIngredientesAssignment_10_1(), "rule__Postre__IngredientesAssignment_10_1");
					put(grammarAccess.getPostreAccess().getIngredientesAssignment_10_2_1(), "rule__Postre__IngredientesAssignment_10_2_1");
					put(grammarAccess.getPostreAccess().getNutricionalAssignment_11_1(), "rule__Postre__NutricionalAssignment_11_1");
					put(grammarAccess.getNutricionalAccess().getCantidadAssignment_2(), "rule__Nutricional__CantidadAssignment_2");
					put(grammarAccess.getNutricionalAccess().getUnidadAssignment_4(), "rule__Nutricional__UnidadAssignment_4");
					put(grammarAccess.getNutricionalAccess().getEnergiaAssignment_6(), "rule__Nutricional__EnergiaAssignment_6");
					put(grammarAccess.getNutricionalAccess().getGrasasAssignment_8(), "rule__Nutricional__GrasasAssignment_8");
					put(grammarAccess.getNutricionalAccess().getHidratosAssignment_10(), "rule__Nutricional__HidratosAssignment_10");
					put(grammarAccess.getNutricionalAccess().getProteinasAssignment_12(), "rule__Nutricional__ProteinasAssignment_12");
					put(grammarAccess.getNutricionalAccess().getSalAssignment_14(), "rule__Nutricional__SalAssignment_14");
					put(grammarAccess.getMenuAccess().getNameAssignment_1(), "rule__Menu__NameAssignment_1");
					put(grammarAccess.getMenuAccess().getNombreAssignment_2(), "rule__Menu__NombreAssignment_2");
					put(grammarAccess.getMenuAccess().getDescripcionAssignment_5(), "rule__Menu__DescripcionAssignment_5");
					put(grammarAccess.getMenuAccess().getTamanioAssignment_7(), "rule__Menu__TamanioAssignment_7");
					put(grammarAccess.getMenuAccess().getFotoAssignment_9(), "rule__Menu__FotoAssignment_9");
					put(grammarAccess.getMenuAccess().getProductosAssignment_10_1(), "rule__Menu__ProductosAssignment_10_1");
					put(grammarAccess.getProductoYAccess().getIzqAssignment_0(), "rule__ProductoY__IzqAssignment_0");
					put(grammarAccess.getProductoYAccess().getDerAssignment_1_1(), "rule__ProductoY__DerAssignment_1_1");
					put(grammarAccess.getProductoOAccess().getIzqAssignment_0(), "rule__ProductoO__IzqAssignment_0");
					put(grammarAccess.getProductoOAccess().getIzqAssignment_1_1(), "rule__ProductoO__IzqAssignment_1_1");
					put(grammarAccess.getProductoOAccess().getDerAssignment_1_2_1(), "rule__ProductoO__DerAssignment_1_2_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RestauranteGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RestauranteGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
