/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.dsl.restaurante.restaurante.BebidaFria;
import org.xtext.dsl.restaurante.restaurante.Distribuidor;
import org.xtext.dsl.restaurante.restaurante.RestaurantePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bebida Fria</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.BebidaFriaImpl#getDistribuidor <em>Distribuidor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BebidaFriaImpl extends BebidaImpl implements BebidaFria
{
  /**
   * The default value of the '{@link #getDistribuidor() <em>Distribuidor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDistribuidor()
   * @generated
   * @ordered
   */
  protected static final Distribuidor DISTRIBUIDOR_EDEFAULT = Distribuidor.COCA_COLA;

  /**
   * The cached value of the '{@link #getDistribuidor() <em>Distribuidor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDistribuidor()
   * @generated
   * @ordered
   */
  protected Distribuidor distribuidor = DISTRIBUIDOR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BebidaFriaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestaurantePackage.Literals.BEBIDA_FRIA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Distribuidor getDistribuidor()
  {
    return distribuidor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDistribuidor(Distribuidor newDistribuidor)
  {
    Distribuidor oldDistribuidor = distribuidor;
    distribuidor = newDistribuidor == null ? DISTRIBUIDOR_EDEFAULT : newDistribuidor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.BEBIDA_FRIA__DISTRIBUIDOR, oldDistribuidor, distribuidor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestaurantePackage.BEBIDA_FRIA__DISTRIBUIDOR:
        return getDistribuidor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestaurantePackage.BEBIDA_FRIA__DISTRIBUIDOR:
        setDistribuidor((Distribuidor)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.BEBIDA_FRIA__DISTRIBUIDOR:
        setDistribuidor(DISTRIBUIDOR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.BEBIDA_FRIA__DISTRIBUIDOR:
        return distribuidor != DISTRIBUIDOR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (distribuidor: ");
    result.append(distribuidor);
    result.append(')');
    return result.toString();
  }

} //BebidaFriaImpl
