/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dsl.restaurante.restaurante.Ingrediente;
import org.xtext.dsl.restaurante.restaurante.RestaurantePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ingrediente</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl#getInfoURL <em>Info URL</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl#getFoto <em>Foto</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl#isAlergenico <em>Alergenico</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IngredienteImpl extends MinimalEObjectImpl.Container implements Ingrediente
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected String nombre = NOMBRE_EDEFAULT;

  /**
   * The default value of the '{@link #getInfoURL() <em>Info URL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInfoURL()
   * @generated
   * @ordered
   */
  protected static final String INFO_URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInfoURL() <em>Info URL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInfoURL()
   * @generated
   * @ordered
   */
  protected String infoURL = INFO_URL_EDEFAULT;

  /**
   * The default value of the '{@link #getFoto() <em>Foto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFoto()
   * @generated
   * @ordered
   */
  protected static final String FOTO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFoto() <em>Foto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFoto()
   * @generated
   * @ordered
   */
  protected String foto = FOTO_EDEFAULT;

  /**
   * The default value of the '{@link #isAlergenico() <em>Alergenico</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAlergenico()
   * @generated
   * @ordered
   */
  protected static final boolean ALERGENICO_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isAlergenico() <em>Alergenico</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAlergenico()
   * @generated
   * @ordered
   */
  protected boolean alergenico = ALERGENICO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IngredienteImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestaurantePackage.Literals.INGREDIENTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.INGREDIENTE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNombre()
  {
    return nombre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNombre(String newNombre)
  {
    String oldNombre = nombre;
    nombre = newNombre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.INGREDIENTE__NOMBRE, oldNombre, nombre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getInfoURL()
  {
    return infoURL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInfoURL(String newInfoURL)
  {
    String oldInfoURL = infoURL;
    infoURL = newInfoURL;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.INGREDIENTE__INFO_URL, oldInfoURL, infoURL));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFoto()
  {
    return foto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFoto(String newFoto)
  {
    String oldFoto = foto;
    foto = newFoto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.INGREDIENTE__FOTO, oldFoto, foto));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isAlergenico()
  {
    return alergenico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAlergenico(boolean newAlergenico)
  {
    boolean oldAlergenico = alergenico;
    alergenico = newAlergenico;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.INGREDIENTE__ALERGENICO, oldAlergenico, alergenico));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestaurantePackage.INGREDIENTE__NAME:
        return getName();
      case RestaurantePackage.INGREDIENTE__NOMBRE:
        return getNombre();
      case RestaurantePackage.INGREDIENTE__INFO_URL:
        return getInfoURL();
      case RestaurantePackage.INGREDIENTE__FOTO:
        return getFoto();
      case RestaurantePackage.INGREDIENTE__ALERGENICO:
        return isAlergenico();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestaurantePackage.INGREDIENTE__NAME:
        setName((String)newValue);
        return;
      case RestaurantePackage.INGREDIENTE__NOMBRE:
        setNombre((String)newValue);
        return;
      case RestaurantePackage.INGREDIENTE__INFO_URL:
        setInfoURL((String)newValue);
        return;
      case RestaurantePackage.INGREDIENTE__FOTO:
        setFoto((String)newValue);
        return;
      case RestaurantePackage.INGREDIENTE__ALERGENICO:
        setAlergenico((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.INGREDIENTE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RestaurantePackage.INGREDIENTE__NOMBRE:
        setNombre(NOMBRE_EDEFAULT);
        return;
      case RestaurantePackage.INGREDIENTE__INFO_URL:
        setInfoURL(INFO_URL_EDEFAULT);
        return;
      case RestaurantePackage.INGREDIENTE__FOTO:
        setFoto(FOTO_EDEFAULT);
        return;
      case RestaurantePackage.INGREDIENTE__ALERGENICO:
        setAlergenico(ALERGENICO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.INGREDIENTE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RestaurantePackage.INGREDIENTE__NOMBRE:
        return NOMBRE_EDEFAULT == null ? nombre != null : !NOMBRE_EDEFAULT.equals(nombre);
      case RestaurantePackage.INGREDIENTE__INFO_URL:
        return INFO_URL_EDEFAULT == null ? infoURL != null : !INFO_URL_EDEFAULT.equals(infoURL);
      case RestaurantePackage.INGREDIENTE__FOTO:
        return FOTO_EDEFAULT == null ? foto != null : !FOTO_EDEFAULT.equals(foto);
      case RestaurantePackage.INGREDIENTE__ALERGENICO:
        return alergenico != ALERGENICO_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nombre: ");
    result.append(nombre);
    result.append(", infoURL: ");
    result.append(infoURL);
    result.append(", foto: ");
    result.append(foto);
    result.append(", alergenico: ");
    result.append(alergenico);
    result.append(')');
    return result.toString();
  }

} //IngredienteImpl
