/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dsl.restaurante.restaurante.Menu;
import org.xtext.dsl.restaurante.restaurante.ProductoY;
import org.xtext.dsl.restaurante.restaurante.RestaurantePackage;
import org.xtext.dsl.restaurante.restaurante.TamanioMenu;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Menu</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.MenuImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.MenuImpl#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.MenuImpl#getDescripcion <em>Descripcion</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.MenuImpl#getTamanio <em>Tamanio</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.MenuImpl#getFoto <em>Foto</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.MenuImpl#getProductos <em>Productos</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MenuImpl extends MinimalEObjectImpl.Container implements Menu
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected String nombre = NOMBRE_EDEFAULT;

  /**
   * The default value of the '{@link #getDescripcion() <em>Descripcion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescripcion()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPCION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescripcion() <em>Descripcion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescripcion()
   * @generated
   * @ordered
   */
  protected String descripcion = DESCRIPCION_EDEFAULT;

  /**
   * The default value of the '{@link #getTamanio() <em>Tamanio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTamanio()
   * @generated
   * @ordered
   */
  protected static final TamanioMenu TAMANIO_EDEFAULT = TamanioMenu.NORMAL;

  /**
   * The cached value of the '{@link #getTamanio() <em>Tamanio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTamanio()
   * @generated
   * @ordered
   */
  protected TamanioMenu tamanio = TAMANIO_EDEFAULT;

  /**
   * The default value of the '{@link #getFoto() <em>Foto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFoto()
   * @generated
   * @ordered
   */
  protected static final String FOTO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFoto() <em>Foto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFoto()
   * @generated
   * @ordered
   */
  protected String foto = FOTO_EDEFAULT;

  /**
   * The cached value of the '{@link #getProductos() <em>Productos</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProductos()
   * @generated
   * @ordered
   */
  protected ProductoY productos;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MenuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestaurantePackage.Literals.MENU;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.MENU__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNombre()
  {
    return nombre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNombre(String newNombre)
  {
    String oldNombre = nombre;
    nombre = newNombre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.MENU__NOMBRE, oldNombre, nombre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDescripcion()
  {
    return descripcion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDescripcion(String newDescripcion)
  {
    String oldDescripcion = descripcion;
    descripcion = newDescripcion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.MENU__DESCRIPCION, oldDescripcion, descripcion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TamanioMenu getTamanio()
  {
    return tamanio;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTamanio(TamanioMenu newTamanio)
  {
    TamanioMenu oldTamanio = tamanio;
    tamanio = newTamanio == null ? TAMANIO_EDEFAULT : newTamanio;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.MENU__TAMANIO, oldTamanio, tamanio));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFoto()
  {
    return foto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFoto(String newFoto)
  {
    String oldFoto = foto;
    foto = newFoto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.MENU__FOTO, oldFoto, foto));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProductoY getProductos()
  {
    return productos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProductos(ProductoY newProductos, NotificationChain msgs)
  {
    ProductoY oldProductos = productos;
    productos = newProductos;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RestaurantePackage.MENU__PRODUCTOS, oldProductos, newProductos);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProductos(ProductoY newProductos)
  {
    if (newProductos != productos)
    {
      NotificationChain msgs = null;
      if (productos != null)
        msgs = ((InternalEObject)productos).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RestaurantePackage.MENU__PRODUCTOS, null, msgs);
      if (newProductos != null)
        msgs = ((InternalEObject)newProductos).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RestaurantePackage.MENU__PRODUCTOS, null, msgs);
      msgs = basicSetProductos(newProductos, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.MENU__PRODUCTOS, newProductos, newProductos));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RestaurantePackage.MENU__PRODUCTOS:
        return basicSetProductos(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestaurantePackage.MENU__NAME:
        return getName();
      case RestaurantePackage.MENU__NOMBRE:
        return getNombre();
      case RestaurantePackage.MENU__DESCRIPCION:
        return getDescripcion();
      case RestaurantePackage.MENU__TAMANIO:
        return getTamanio();
      case RestaurantePackage.MENU__FOTO:
        return getFoto();
      case RestaurantePackage.MENU__PRODUCTOS:
        return getProductos();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestaurantePackage.MENU__NAME:
        setName((String)newValue);
        return;
      case RestaurantePackage.MENU__NOMBRE:
        setNombre((String)newValue);
        return;
      case RestaurantePackage.MENU__DESCRIPCION:
        setDescripcion((String)newValue);
        return;
      case RestaurantePackage.MENU__TAMANIO:
        setTamanio((TamanioMenu)newValue);
        return;
      case RestaurantePackage.MENU__FOTO:
        setFoto((String)newValue);
        return;
      case RestaurantePackage.MENU__PRODUCTOS:
        setProductos((ProductoY)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.MENU__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RestaurantePackage.MENU__NOMBRE:
        setNombre(NOMBRE_EDEFAULT);
        return;
      case RestaurantePackage.MENU__DESCRIPCION:
        setDescripcion(DESCRIPCION_EDEFAULT);
        return;
      case RestaurantePackage.MENU__TAMANIO:
        setTamanio(TAMANIO_EDEFAULT);
        return;
      case RestaurantePackage.MENU__FOTO:
        setFoto(FOTO_EDEFAULT);
        return;
      case RestaurantePackage.MENU__PRODUCTOS:
        setProductos((ProductoY)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.MENU__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RestaurantePackage.MENU__NOMBRE:
        return NOMBRE_EDEFAULT == null ? nombre != null : !NOMBRE_EDEFAULT.equals(nombre);
      case RestaurantePackage.MENU__DESCRIPCION:
        return DESCRIPCION_EDEFAULT == null ? descripcion != null : !DESCRIPCION_EDEFAULT.equals(descripcion);
      case RestaurantePackage.MENU__TAMANIO:
        return tamanio != TAMANIO_EDEFAULT;
      case RestaurantePackage.MENU__FOTO:
        return FOTO_EDEFAULT == null ? foto != null : !FOTO_EDEFAULT.equals(foto);
      case RestaurantePackage.MENU__PRODUCTOS:
        return productos != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nombre: ");
    result.append(nombre);
    result.append(", descripcion: ");
    result.append(descripcion);
    result.append(", tamanio: ");
    result.append(tamanio);
    result.append(", foto: ");
    result.append(foto);
    result.append(')');
    return result.toString();
  }

} //MenuImpl
