/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dsl.restaurante.restaurante.Nutricional;
import org.xtext.dsl.restaurante.restaurante.RestaurantePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Nutricional</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl#getCantidad <em>Cantidad</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl#getUnidad <em>Unidad</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl#getEnergia <em>Energia</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl#getGrasas <em>Grasas</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl#getHidratos <em>Hidratos</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl#getProteinas <em>Proteinas</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.NutricionalImpl#getSal <em>Sal</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NutricionalImpl extends MinimalEObjectImpl.Container implements Nutricional
{
  /**
   * The default value of the '{@link #getCantidad() <em>Cantidad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCantidad()
   * @generated
   * @ordered
   */
  protected static final String CANTIDAD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCantidad() <em>Cantidad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCantidad()
   * @generated
   * @ordered
   */
  protected String cantidad = CANTIDAD_EDEFAULT;

  /**
   * The default value of the '{@link #getUnidad() <em>Unidad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnidad()
   * @generated
   * @ordered
   */
  protected static final String UNIDAD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUnidad() <em>Unidad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnidad()
   * @generated
   * @ordered
   */
  protected String unidad = UNIDAD_EDEFAULT;

  /**
   * The default value of the '{@link #getEnergia() <em>Energia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnergia()
   * @generated
   * @ordered
   */
  protected static final String ENERGIA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnergia() <em>Energia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnergia()
   * @generated
   * @ordered
   */
  protected String energia = ENERGIA_EDEFAULT;

  /**
   * The default value of the '{@link #getGrasas() <em>Grasas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrasas()
   * @generated
   * @ordered
   */
  protected static final String GRASAS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGrasas() <em>Grasas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrasas()
   * @generated
   * @ordered
   */
  protected String grasas = GRASAS_EDEFAULT;

  /**
   * The default value of the '{@link #getHidratos() <em>Hidratos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidratos()
   * @generated
   * @ordered
   */
  protected static final String HIDRATOS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHidratos() <em>Hidratos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidratos()
   * @generated
   * @ordered
   */
  protected String hidratos = HIDRATOS_EDEFAULT;

  /**
   * The default value of the '{@link #getProteinas() <em>Proteinas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProteinas()
   * @generated
   * @ordered
   */
  protected static final String PROTEINAS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getProteinas() <em>Proteinas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProteinas()
   * @generated
   * @ordered
   */
  protected String proteinas = PROTEINAS_EDEFAULT;

  /**
   * The default value of the '{@link #getSal() <em>Sal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSal()
   * @generated
   * @ordered
   */
  protected static final String SAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSal() <em>Sal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSal()
   * @generated
   * @ordered
   */
  protected String sal = SAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NutricionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestaurantePackage.Literals.NUTRICIONAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCantidad()
  {
    return cantidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCantidad(String newCantidad)
  {
    String oldCantidad = cantidad;
    cantidad = newCantidad;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.NUTRICIONAL__CANTIDAD, oldCantidad, cantidad));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUnidad()
  {
    return unidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnidad(String newUnidad)
  {
    String oldUnidad = unidad;
    unidad = newUnidad;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.NUTRICIONAL__UNIDAD, oldUnidad, unidad));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEnergia()
  {
    return energia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnergia(String newEnergia)
  {
    String oldEnergia = energia;
    energia = newEnergia;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.NUTRICIONAL__ENERGIA, oldEnergia, energia));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getGrasas()
  {
    return grasas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGrasas(String newGrasas)
  {
    String oldGrasas = grasas;
    grasas = newGrasas;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.NUTRICIONAL__GRASAS, oldGrasas, grasas));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getHidratos()
  {
    return hidratos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHidratos(String newHidratos)
  {
    String oldHidratos = hidratos;
    hidratos = newHidratos;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.NUTRICIONAL__HIDRATOS, oldHidratos, hidratos));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getProteinas()
  {
    return proteinas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProteinas(String newProteinas)
  {
    String oldProteinas = proteinas;
    proteinas = newProteinas;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.NUTRICIONAL__PROTEINAS, oldProteinas, proteinas));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSal()
  {
    return sal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSal(String newSal)
  {
    String oldSal = sal;
    sal = newSal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.NUTRICIONAL__SAL, oldSal, sal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestaurantePackage.NUTRICIONAL__CANTIDAD:
        return getCantidad();
      case RestaurantePackage.NUTRICIONAL__UNIDAD:
        return getUnidad();
      case RestaurantePackage.NUTRICIONAL__ENERGIA:
        return getEnergia();
      case RestaurantePackage.NUTRICIONAL__GRASAS:
        return getGrasas();
      case RestaurantePackage.NUTRICIONAL__HIDRATOS:
        return getHidratos();
      case RestaurantePackage.NUTRICIONAL__PROTEINAS:
        return getProteinas();
      case RestaurantePackage.NUTRICIONAL__SAL:
        return getSal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestaurantePackage.NUTRICIONAL__CANTIDAD:
        setCantidad((String)newValue);
        return;
      case RestaurantePackage.NUTRICIONAL__UNIDAD:
        setUnidad((String)newValue);
        return;
      case RestaurantePackage.NUTRICIONAL__ENERGIA:
        setEnergia((String)newValue);
        return;
      case RestaurantePackage.NUTRICIONAL__GRASAS:
        setGrasas((String)newValue);
        return;
      case RestaurantePackage.NUTRICIONAL__HIDRATOS:
        setHidratos((String)newValue);
        return;
      case RestaurantePackage.NUTRICIONAL__PROTEINAS:
        setProteinas((String)newValue);
        return;
      case RestaurantePackage.NUTRICIONAL__SAL:
        setSal((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.NUTRICIONAL__CANTIDAD:
        setCantidad(CANTIDAD_EDEFAULT);
        return;
      case RestaurantePackage.NUTRICIONAL__UNIDAD:
        setUnidad(UNIDAD_EDEFAULT);
        return;
      case RestaurantePackage.NUTRICIONAL__ENERGIA:
        setEnergia(ENERGIA_EDEFAULT);
        return;
      case RestaurantePackage.NUTRICIONAL__GRASAS:
        setGrasas(GRASAS_EDEFAULT);
        return;
      case RestaurantePackage.NUTRICIONAL__HIDRATOS:
        setHidratos(HIDRATOS_EDEFAULT);
        return;
      case RestaurantePackage.NUTRICIONAL__PROTEINAS:
        setProteinas(PROTEINAS_EDEFAULT);
        return;
      case RestaurantePackage.NUTRICIONAL__SAL:
        setSal(SAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.NUTRICIONAL__CANTIDAD:
        return CANTIDAD_EDEFAULT == null ? cantidad != null : !CANTIDAD_EDEFAULT.equals(cantidad);
      case RestaurantePackage.NUTRICIONAL__UNIDAD:
        return UNIDAD_EDEFAULT == null ? unidad != null : !UNIDAD_EDEFAULT.equals(unidad);
      case RestaurantePackage.NUTRICIONAL__ENERGIA:
        return ENERGIA_EDEFAULT == null ? energia != null : !ENERGIA_EDEFAULT.equals(energia);
      case RestaurantePackage.NUTRICIONAL__GRASAS:
        return GRASAS_EDEFAULT == null ? grasas != null : !GRASAS_EDEFAULT.equals(grasas);
      case RestaurantePackage.NUTRICIONAL__HIDRATOS:
        return HIDRATOS_EDEFAULT == null ? hidratos != null : !HIDRATOS_EDEFAULT.equals(hidratos);
      case RestaurantePackage.NUTRICIONAL__PROTEINAS:
        return PROTEINAS_EDEFAULT == null ? proteinas != null : !PROTEINAS_EDEFAULT.equals(proteinas);
      case RestaurantePackage.NUTRICIONAL__SAL:
        return SAL_EDEFAULT == null ? sal != null : !SAL_EDEFAULT.equals(sal);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (cantidad: ");
    result.append(cantidad);
    result.append(", unidad: ");
    result.append(unidad);
    result.append(", energia: ");
    result.append(energia);
    result.append(", grasas: ");
    result.append(grasas);
    result.append(", hidratos: ");
    result.append(hidratos);
    result.append(", proteinas: ");
    result.append(proteinas);
    result.append(", sal: ");
    result.append(sal);
    result.append(')');
    return result.toString();
  }

} //NutricionalImpl
