/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.dsl.restaurante.restaurante.Ingrediente;
import org.xtext.dsl.restaurante.restaurante.Principal;
import org.xtext.dsl.restaurante.restaurante.RestaurantePackage;
import org.xtext.dsl.restaurante.restaurante.SalsaRecomendada;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Principal</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.PrincipalImpl#isEnsalada <em>Ensalada</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.PrincipalImpl#getIngredientes <em>Ingredientes</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.PrincipalImpl#getSalsa <em>Salsa</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrincipalImpl extends ProductoImpl implements Principal
{
  /**
   * The default value of the '{@link #isEnsalada() <em>Ensalada</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEnsalada()
   * @generated
   * @ordered
   */
  protected static final boolean ENSALADA_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEnsalada() <em>Ensalada</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEnsalada()
   * @generated
   * @ordered
   */
  protected boolean ensalada = ENSALADA_EDEFAULT;

  /**
   * The cached value of the '{@link #getIngredientes() <em>Ingredientes</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIngredientes()
   * @generated
   * @ordered
   */
  protected EList<Ingrediente> ingredientes;

  /**
   * The default value of the '{@link #getSalsa() <em>Salsa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSalsa()
   * @generated
   * @ordered
   */
  protected static final SalsaRecomendada SALSA_EDEFAULT = SalsaRecomendada.NINGUNA;

  /**
   * The cached value of the '{@link #getSalsa() <em>Salsa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSalsa()
   * @generated
   * @ordered
   */
  protected SalsaRecomendada salsa = SALSA_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrincipalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestaurantePackage.Literals.PRINCIPAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isEnsalada()
  {
    return ensalada;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnsalada(boolean newEnsalada)
  {
    boolean oldEnsalada = ensalada;
    ensalada = newEnsalada;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.PRINCIPAL__ENSALADA, oldEnsalada, ensalada));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Ingrediente> getIngredientes()
  {
    if (ingredientes == null)
    {
      ingredientes = new EObjectResolvingEList<Ingrediente>(Ingrediente.class, this, RestaurantePackage.PRINCIPAL__INGREDIENTES);
    }
    return ingredientes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SalsaRecomendada getSalsa()
  {
    return salsa;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSalsa(SalsaRecomendada newSalsa)
  {
    SalsaRecomendada oldSalsa = salsa;
    salsa = newSalsa == null ? SALSA_EDEFAULT : newSalsa;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.PRINCIPAL__SALSA, oldSalsa, salsa));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestaurantePackage.PRINCIPAL__ENSALADA:
        return isEnsalada();
      case RestaurantePackage.PRINCIPAL__INGREDIENTES:
        return getIngredientes();
      case RestaurantePackage.PRINCIPAL__SALSA:
        return getSalsa();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestaurantePackage.PRINCIPAL__ENSALADA:
        setEnsalada((Boolean)newValue);
        return;
      case RestaurantePackage.PRINCIPAL__INGREDIENTES:
        getIngredientes().clear();
        getIngredientes().addAll((Collection<? extends Ingrediente>)newValue);
        return;
      case RestaurantePackage.PRINCIPAL__SALSA:
        setSalsa((SalsaRecomendada)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.PRINCIPAL__ENSALADA:
        setEnsalada(ENSALADA_EDEFAULT);
        return;
      case RestaurantePackage.PRINCIPAL__INGREDIENTES:
        getIngredientes().clear();
        return;
      case RestaurantePackage.PRINCIPAL__SALSA:
        setSalsa(SALSA_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.PRINCIPAL__ENSALADA:
        return ensalada != ENSALADA_EDEFAULT;
      case RestaurantePackage.PRINCIPAL__INGREDIENTES:
        return ingredientes != null && !ingredientes.isEmpty();
      case RestaurantePackage.PRINCIPAL__SALSA:
        return salsa != SALSA_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (ensalada: ");
    result.append(ensalada);
    result.append(", salsa: ");
    result.append(salsa);
    result.append(')');
    return result.toString();
  }

} //PrincipalImpl
