/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.restaurante.restaurante.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.dsl.restaurante.restaurante.Producto;
import org.xtext.dsl.restaurante.restaurante.ProductoO;
import org.xtext.dsl.restaurante.restaurante.RestaurantePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Producto O</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.ProductoOImpl#getIzq <em>Izq</em>}</li>
 *   <li>{@link org.xtext.dsl.restaurante.restaurante.impl.ProductoOImpl#getDer <em>Der</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProductoOImpl extends MinimalEObjectImpl.Container implements ProductoO
{
  /**
   * The cached value of the '{@link #getIzq() <em>Izq</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIzq()
   * @generated
   * @ordered
   */
  protected Producto izq;

  /**
   * The cached value of the '{@link #getDer() <em>Der</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDer()
   * @generated
   * @ordered
   */
  protected EList<Producto> der;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProductoOImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestaurantePackage.Literals.PRODUCTO_O;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Producto getIzq()
  {
    if (izq != null && izq.eIsProxy())
    {
      InternalEObject oldIzq = (InternalEObject)izq;
      izq = (Producto)eResolveProxy(oldIzq);
      if (izq != oldIzq)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RestaurantePackage.PRODUCTO_O__IZQ, oldIzq, izq));
      }
    }
    return izq;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Producto basicGetIzq()
  {
    return izq;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIzq(Producto newIzq)
  {
    Producto oldIzq = izq;
    izq = newIzq;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestaurantePackage.PRODUCTO_O__IZQ, oldIzq, izq));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Producto> getDer()
  {
    if (der == null)
    {
      der = new EObjectResolvingEList<Producto>(Producto.class, this, RestaurantePackage.PRODUCTO_O__DER);
    }
    return der;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestaurantePackage.PRODUCTO_O__IZQ:
        if (resolve) return getIzq();
        return basicGetIzq();
      case RestaurantePackage.PRODUCTO_O__DER:
        return getDer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestaurantePackage.PRODUCTO_O__IZQ:
        setIzq((Producto)newValue);
        return;
      case RestaurantePackage.PRODUCTO_O__DER:
        getDer().clear();
        getDer().addAll((Collection<? extends Producto>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.PRODUCTO_O__IZQ:
        setIzq((Producto)null);
        return;
      case RestaurantePackage.PRODUCTO_O__DER:
        getDer().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestaurantePackage.PRODUCTO_O__IZQ:
        return izq != null;
      case RestaurantePackage.PRODUCTO_O__DER:
        return der != null && !der.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ProductoOImpl
